### ISSUE TITLE
Search for Runs table not working

### ISSUE THREAD

**Issue by mdietze** [PecanProject/bety#111]
When I type search teams in the search window on the Runs table, either all the entries go grey (and none ever return as selected) or the page crashes. Typically I am searching for words in the the Parameters List, which are in the table itself (e.g. trying to find the runs that were sensitivity analyses for SLA).  

It would also be nice to search for specific sites as well, but that understandably is a tad harder since the site names are in a different table.

**Comment by dlebauer** [comment]
This was resolved in BETYdb 3.3 https://github.com/PecanProject/bety/releases/tag/betydb_3.3
