### ISSUE TITLE
Search for Inputs table not working 

### ISSUE THREAD

**Issue by bcow** [PecanProject/bety#121]
Just like previous search problems:
When typing search teams in the search window on the Inputs table, all the entries go grey. 
After typing in a search and hitting enter, the following error is displayed:

"We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly."

**Comment by dlebauer** [comment]
Fixed in BETYdb 3.3 https://github.com/PecanProject/bety/releases/tag/betydb_3.3
