### ISSUE TITLE
Re-align fields in species/show page 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#135]
* remove "Plant"
* Move USDA Species Symbol to the end
* USDA Species Symbol should be populated with "AcceptedSymbol" field

![image](https://cloud.githubusercontent.com/assets/464871/4141644/2d1f99e6-33b0-11e4-8716-b7a711c3f931.png)

refs #75; [RM-2211](https://ebi-forecast.igb.illinois.edu/redmine/issues/2211)

**Comment by gsrohde** [comment]
Released in version 4.2.
