### ISSUE TITLE
Cloning PFT with Ruby 2.0 gives `NoMethodError`

### ISSUE THREAD

**Issue by robkooper** [PecanProject/bety#141]
When using Ruby 2.0,

When cloning a pft record you will get the following error : `NoMethodError: undefined method 'insert_record' for #<Array:0x000000052541f8> from `, 

This is due to the fact that ruby 2.0 does not have that function anymore, or something else. See also https://github.com/rails/rails/issues/11026. 

Upgrading from rails 3.0.18 to 3.2.19 (latest in 3 series) will solve this problem, but create new ones: 1) rjs will not work and opening of species etc will not work.

**Comment by gsrohde** [comment]
Not an issue (I think!)--we now officially support Ruby version 2.1.5, but anything >= 1.9.3 probably works.
