### ISSUE TITLE
Design database changes required to restrict pfts to specific cultivars 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#145]
I would appreciate feedback on the following changes to the database schema.

I have come up with two possible options (see below), and would appreciate feedback - especially from @mdietze, @robkooper, @gsrohde 

This task requires

1. [ ] create the resulting ER diagram to represent the new table (and 1st degree relations)
2. [ ] review to make sure that this is logical and select one of the options below?
3. [ ] update PecanProject/pecan#227 with new `where cultivar_id = ...`

**Comment by gsrohde** [comment]
@dlebauer Can I close this?

**Comment by dlebauer** [comment]
Yes, this can be closed though to addresss the valid points raised by @mdietze:
1. if there is a case where research conflicts with the constraints, we can remove the constraint. 
2. we can address issues with the interface at the time of implementation;
