### ISSUE TITLE
Review and update overleaf document on constraints

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#149]
Please see explanation and list of constraints on the [BETYdb Constraints](https://authorea.com/users/5574/articles/6719/_show_article) document

* Combine other text written by @gsrohde from Box into the BETYdb Constraints document

**Comment by gsrohde** [comment]
I moved the authorea documentation to overleaf.  The read-only version is at https://www.overleaf.com/read/wxptyrksypkx

To edit, go to https://www.overleaf.com/2086241dwjyrd

**Comment by gsrohde** [comment]
@dlebauer Originally I had thought of this as a working document--something to use only while we were in the process of designing and implementing constraints.  But then I got the impression you were thinking of it as something more permanent, perhaps even as something that would become a significant piece of the database documentation.  If this is true, it seems it will gradually need to be rewritten as we implement those constraints.  (Even the first sentence--"We are proposing implementation of database-level constraints"--is by now anachronistic.  "We have decided to implement database-level constraints and are now in the process of doing so" is more accurate at this point, and even this will presumably be outdated when we are done.)

Could you clarify your intended purpose for this document?

**Comment by dlebauer** [comment]
The idea was first to serve as a proposal that could be reviewed and developed, and later to serve as documentation that that both gives background and an list of the specific constraints that we applied. The tense is not nearly as important as the background and details, and to have all of these details in one place (or linked to from one place). I just assume the .tex file go in the BETYdb repository, but the overleaf provides a simple interface for editing and compiling.
