### ISSUE TITLE
how can I query all switchgrass yields with fertilization rates

### ISSUE THREAD

**Issue by bkrohn** [PecanProject/bety#157]
Hi, 

I am researching switchgrass and would like to query fertilization rates, yield, ecotype, and lat/long.  I've gotten yield but haven't found fertilization rates.  Can anyone help?

**Comment by dlebauer** [comment]
Sorry it took so long to get back to you, but hopefully this will answer your question!

https://github.com/ebimodeling/betydb_manuscript/blob/master/fig4a_with_ropensci_traits_package.Rmd
