### ISSUE TITLE
Auto-increment pft name when creating a clone

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#158]
On the pfts show page, when creating a clone, the name is duplicated.

Ideally, the user who 'clones' would be prompted (required?) to create a meaningful name. This could be done by simply not allowing the new pft to be saved until a new name is created.

The easiest solution would be to auto-increment the name field by default (i.e. plants --> plants2). Or maybe plants_clone1, plants_clone2. However, this would promote 'lazy' behavior that would result in lots of duplicate pfts that are difficult to distinguish.

**Comment by robkooper** [comment]
I think a cleaner way is for the clone button to have a field next to it that has to have the new name, and has to be unique, otherwise it comes back and shows a message that the name is not unique (maybe with a link to the pft with that specific name).

**Comment by dlebauer** [comment]
@robkooper good idea

**Comment by gsrohde** [comment]
@dlebauer @robkooper Here's where things are at with this: Right now, pressing "Clone Record" on the "show" page creates a new PFT that is just like the one you cloned from except the name has "-copy" appended to it.  And you land on the "show" page for the copy.  If you want to give it a new name, you can then press the "Edit Record" button, change the name in the "Name" field, and press the "Update" button.

Do we want to do anything more with this?

**Comment by dlebauer** [comment]
that works. I think the important point is that it doesn't create two pfts with the same name

**Comment by robkooper** [comment]
What happens if I create a second copy?

**Comment by gsrohde** [comment]
It will get the name originalname-copy-copy.

**Comment by gsrohde** [comment]
Actually, I don't know what will happen if you go back to the original and make a second clone of it, but I suspect you will get an error unless you renamed originalname-copy to something else before doing so.  This is the same as if you tried to make a new PFT re-using an existing name.

**Comment by dlebauer** [comment]
Would it be sufficient for the error to say 'name already in use' (as with
most website usernames)?
