### ISSUE TITLE
latitude range should be [-90, 90]

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#161]
In 471b893df7573539403cc0e00a5e7b16265f69a0, @robkooper added lat and lon fields to the traits and yields views

It does appear that the records with lat out of range have had the lat and lon switched. However, this did not appear prior to the conversion to PostgreSQL.

```sql
                         ST_Y(ST_Centroid(sites.geometry)) AS lat,
                         ST_X(ST_Centroid(sites.geometry)) AS lon,
```

However, for some reason this results in some sites with latitudes that are out of bounds ([source](https://gist.github.com/dlebauer/7cf1d8727cf8e501b03e)):

![image](https://cloud.githubusercontent.com/assets/464871/5652073/c1d83028-9672-11e4-8979-db9ceed8f616.png)

**Comment by robkooper** [comment]
David I think is due to your code (https://gist.github.com/dlebauer/e76c6bec32b1d29f1a16) I think you inserted the lat/lon in the wrong order. ST_MakePoint takes 2 arguments X,Y which is lon/lat. A quick check shows that some of the values that fail the constraints are those that are in this gist.

**Comment by dlebauer** [comment]
I'll look into this- thanks for identifying the likely source of this error ... I'll review it tomorrow. Howver, according to [the documentation](http://postgis.net/docs/ST_MakePoint.html), ST_MakePoint can take an optional third argument, z. elevation, as well as a fourth, m, but I may have applied it incorrectly.

**Comment by dlebauer** [comment]
Ah, now I see, _wrong order_. At least it will be an easy fix

**Comment by dlebauer** [comment]
Should be fixed by the queries here: https://gist.github.com/dlebauer/e76c6bec32b1d29f1a16#file-update_sites_switch_latlon-sql

Looks much better:

![image](https://cloud.githubusercontent.com/assets/464871/5667630/ef59a204-972e-11e4-9d39-4ae8494f14f0.png)
