### ISSUE TITLE
citations_sites: missing sites

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#164]
select site_id, count(*), array_agg(citation_id) as citation_id_list from citations_sites where site_id not in (select id from sites) group by site_id;
 site_id | count | citation_id_list 
---------+-------+------------------
      46 |     1 | {290}
     559 |     1 | {276}
     570 |     1 | {216}
     660 |     1 | {253}
    1085 |     1 | {712}
    1087 |     1 | {712}
    1121 |     1 | {735}
    1129 |     1 | {489}
    1154 |     1 | {751}
    1188 |     1 | {692}
    1197 |     1 | {659}
    1198 |     1 | {659}
    1199 |     1 | {659}
    1200 |     1 | {659}
    1201 |     1 | {659}
    1224 |     1 | {733}
(16 rows)

**Comment by dlebauer** [comment]
These were duplicates of EBI farm plots:

```
delete from citations_sites where site_id between 1197 and 1201 and citation_id = 659
```

This site was entered as a test

```
delete from sites where id = 781
delete from citations_sites where site_id = 781
delete from traits where id = 51203
```
