### ISSUE TITLE
covariates: missing traits and/or variables

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#166]
BOTH MISSING:
select trait_id, variable_id from covariates where trait_id not in (select id from traits) and variable_id not in (select id from variables);
 trait_id | variable_id 
----------+-------------
(0 rows)

TRAIT MISSING:

select trait_id, count(*), array_agg(variable_id) as variable_id_list from covariates where trait_id not in (select id from traits) and variable_id in (select id from variables) group by trait_id order by trait_id;
 trait_id | count |     variable_id_list      
----------+-------+---------------------------
    10319 |     2 | {136,81}
    10320 |     2 | {136,81}
    10321 |     2 | {136,81}
    10322 |     2 | {136,81}
    10323 |     2 | {136,81}
    10324 |     2 | {136,81}
    10325 |     2 | {136,81}
    10326 |     2 | {136,81}
    10327 |     2 | {136,81}
    10328 |     2 | {136,81}
    10329 |     2 | {136,81}
    10330 |     2 | {136,81}
    10331 |     2 | {136,81}
    10332 |     2 | {136,81}
    10333 |     2 | {136,81}
    10334 |     2 | {136,81}
    10335 |     2 | {136,81}
    10336 |     2 | {136,81}
    10337 |     2 | {136,81}
    10338 |     2 | {136,81}
    10339 |     2 | {136,81}
    10340 |     2 | {136,81}
    10341 |     2 | {136,81}
    10342 |     2 | {136,81}
    10343 |     2 | {136,81}
    10344 |     2 | {136,81}
    10345 |     2 | {136,81}
    10346 |     2 | {136,81}
    10347 |     2 | {136,81}
    10348 |     2 | {136,81}
    10349 |     2 | {136,81}
    10350 |     2 | {136,81}
    10351 |     2 | {136,81}
    10352 |     2 | {136,81}
    10353 |     2 | {136,81}
    10354 |     2 | {136,81}
    10355 |     2 | {136,81}
    10356 |     2 | {136,81}
    10357 |     2 | {136,81}
    10358 |     2 | {136,81}
    10359 |     2 | {136,81}
    10360 |     2 | {136,81}
    22163 |     1 | {86}
    22249 |     1 | {208}
    22250 |     1 | {208}
    36184 |     1 | {136}
    36185 |     1 | {136}
    36186 |     1 | {136}
    36187 |     1 | {136}
    36188 |     1 | {136}
    36189 |     1 | {136}
    36190 |     1 | {136}
    36191 |     1 | {136}
    36192 |     1 | {136}
    36193 |     1 | {136}
    36194 |     1 | {136}
    36195 |     1 | {136}
    36196 |     1 | {136}
    36197 |     1 | {136}
    36198 |     1 | {136}
    36199 |     1 | {136}
    36200 |     1 | {136}
    36201 |     1 | {136}
    36202 |     1 | {136}
    36203 |     1 | {136}
    36204 |     1 | {136}
    36205 |     1 | {136}
    36206 |     1 | {136}
    36207 |     1 | {136}
    36208 |     1 | {136}
    36209 |     1 | {136}
    36210 |     1 | {136}
    36211 |     1 | {136}
    36212 |     1 | {136}
    36214 |     1 | {136}
    36215 |     1 | {136}
    36216 |     1 | {136}
    36217 |     1 | {136}
    36218 |     1 | {136}
    36219 |     1 | {136}
    36220 |     1 | {136}
    36221 |     1 | {136}
    36222 |     1 | {136}
    36223 |     1 | {136}
    36224 |     1 | {136}
    36225 |     1 | {136}
    36226 |     1 | {136}
    36227 |     1 | {136}
    36228 |     1 | {136}
    36229 |     1 | {136}
    36230 |     1 | {136}
    36231 |     1 | {136}
    36232 |     1 | {136}
    36233 |     1 | {136}
    36234 |     1 | {136}
    36235 |     1 | {136}
    36236 |     1 | {136}
    36237 |     1 | {136}
    36238 |     1 | {136}
    36239 |     1 | {136}
    36240 |     1 | {136}
    36241 |     1 | {136}
    36242 |     1 | {136}
    36347 |     4 | {208,482,483,486}
    36348 |     4 | {208,482,483,486}
    36349 |     4 | {208,482,483,486}
    36350 |     4 | {208,482,483,486}
    36351 |     4 | {208,482,483,486}
    36355 |     4 | {208,482,483,486}
    36356 |     4 | {208,482,483,486}
    36357 |     4 | {208,482,483,486}
    36358 |     4 | {208,482,483,486}
    36360 |     4 | {208,482,483,486}
    38658 |     6 | {150,208,243,482,483,485}
    41558 |     1 | {356}
    41559 |     1 | {356}
    41560 |     1 | {356}
    41561 |     1 | {356}
    41562 |     1 | {356}
    41563 |     1 | {356}
    41564 |     1 | {356}
    41565 |     1 | {356}
    41566 |     1 | {356}
    41567 |     1 | {356}
    41568 |     1 | {356}
    41569 |     1 | {356}
    41570 |     1 | {356}
    41571 |     1 | {356}
    41572 |     1 | {356}
    41573 |     1 | {356}
    41574 |     1 | {356}
    41575 |     1 | {356}
    41576 |     1 | {356}
    41577 |     1 | {356}
    41578 |     1 | {356}
    41579 |     1 | {356}
    41580 |     1 | {356}
    41581 |     1 | {356}
    41582 |     1 | {356}
    41583 |     1 | {356}
    41584 |     1 | {356}
    41585 |     1 | {356}
    41586 |     1 | {356}
    41587 |     1 | {356}
    41588 |     1 | {356}
    41589 |     1 | {356}
    41590 |     1 | {356}
    41591 |     1 | {356}
    41592 |     1 | {356}
    41593 |     1 | {356}
    41594 |     1 | {356}
    41595 |     1 | {356}
    41596 |     1 | {356}
    41597 |     1 | {356}
    41598 |     1 | {356}
    41599 |     1 | {356}
    41600 |     1 | {356}
    41601 |     1 | {356}
    41602 |     1 | {356}
    41603 |     1 | {356}
    41604 |     1 | {356}
    41605 |     1 | {356}
    41606 |     1 | {356}
    41607 |     1 | {356}
    41608 |     1 | {356}
    41609 |     1 | {356}
    41610 |     1 | {356}
    41611 |     1 | {356}
    41612 |     1 | {356}
    41613 |     1 | {356}
    41614 |     1 | {356}
    41615 |     1 | {356}
    41616 |     1 | {356}
    41617 |     1 | {356}
    41618 |     1 | {356}
    41619 |     1 | {356}
    41620 |     1 | {356}
    41621 |     1 | {356}
    41622 |     1 | {356}
    41623 |     1 | {356}
    41624 |     1 | {356}
    41625 |     1 | {356}
    41626 |     1 | {83}
    41933 |     1 | {356}
    41934 |     1 | {356}
    41935 |     1 | {356}
    41936 |     1 | {356}
    41937 |     1 | {356}
    41938 |     1 | {356}
    41939 |     1 | {356}
    41941 |     1 | {356}
    41944 |     1 | {356}
    41945 |     1 | {356}
    41947 |     1 | {356}
    41950 |     1 | {356}
    41952 |     1 | {356}
    41953 |     1 | {356}
    41955 |     1 | {356}
    41956 |     1 | {356}
    41959 |     1 | {356}
    41965 |     1 | {356}
    41967 |     1 | {356}
    41969 |     1 | {356}
    41971 |     1 | {356}
    41972 |     1 | {356}
    41975 |     1 | {356}
    41983 |     1 | {356}
    41985 |     1 | {356}
    41986 |     1 | {356}
    44130 |     2 | {243,208}
    44131 |     2 | {208,243}
    44132 |     2 | {243,208}
    44133 |     2 | {243,208}
    44134 |     2 | {243,208}
    44340 |     1 | {191}
    44356 |     1 | {191}
    44628 |     1 | {81}
    44762 |     2 | {391,379}
    44868 |     1 | {391}
    45398 |     2 | {398,399}
    45399 |     2 | {398,399}
    45669 |     1 | {86}
    44762 |     2 | {391,379}
    44868 |     1 | {391}
    45398 |     2 | {398,399}
    45399 |     2 | {398,399}
    45669 |     1 | {86}
    45672 |     1 | {81}
    45678 |     1 | {86}
    48340 |     1 | {191}
    48394 |     1 | {191}
    48600 |     2 | {191,191}
    48670 |     2 | {191,191}
    48803 |     1 | {379}
    48845 |     1 | {191}
    48880 |     1 | {191}
    49268 |     1 | {399}
    49298 |     1 | {289}
    49366 |     1 | {398}
    49469 |     1 | {191}
    49542 |     1 | {398}
    49543 |     2 | {398,399}
    49588 |     1 | {191}
    49589 |     1 | {191}
    49741 |     1 | {243}
    49744 |     1 | {243}
    49746 |     1 | {399}
    49878 |     2 | {81,83}
    49880 |     2 | {81,83}
    49995 |     1 | {219}
    50152 |     1 | {398}
    50553 |     1 | {538}
(247 rows)

MISSING VARIABLES:

 select variable_id, count(*), array_agg(trait_id) as trait_id_list from covariates where trait_id in (select id from traits) and variable_id not in (select id from variables) group by variable_id order by variable_id;
 variable_id | count | trait_id_list 
-------------+-------+---------------
           1 |     1 | {2}
         230 |     1 | {36083}
(2 rows)

**Comment by dlebauer** [comment]
All orphaned covariates deleted
```sql
delete from covariates where trait_id not in (select id from traits)
```

and those with missing variables (this record was not valid)

```sql
delete from traits where id = 36083
delete from covariates where trait_id = 36083
```
