### ISSUE TITLE
cultivars: missing species

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#167]
select id, specie_id, name, ecotype, notes from cultivars where specie_id not in (select id from species) order by id;
 id  | specie_id |     name     | ecotype |                        notes                         
-----+-----------+--------------+---------+------------------------------------------------------
  83 |         0 |              |         | 
  84 |         0 |              |         | 
  85 |         0 | Greenville   |         | 
  86 |         0 | I 69         |         | I69 is a clone (populus deltoides, Bartr. cv. "Lux")
  88 |         0 | NL-80351     |         | A hybrid of clone I-69 and clone I-63\r             +
     |           |              |         | (P. deltoides Bartr. cv. "Havard")
  89 |         0 | test         | test    | test
  97 |         0 | 910,51       |         | 
 103 |         0 | Balsam Spire |         | 
 116 |         0 | Wolterson    |         | 
 117 |         0 | Balsam Spire |         | 
 138 |         0 | S25          |         | 
 139 |         0 | S365         |         | 
 140 |         0 | SX61         |         | 
 141 |         0 | SX64         |         | 
 142 |         0 | SX67         |         | 
 143 |         0 | S546         |         | 
 152 |         0 | Wolterson    |         | 
 161 |         0 | 0036-Hrusky  |         | 
 182 |         0 | SA2          |         | 
 215 |         0 | 747210       |         | 
 250 |         0 | 71.015/1     |         | 
 255 |         0 | Androscoggin |         | 
 256 |         0 | Hybride 275  |         | 
 257 |         0 | Hybride 276  |         | 
 258 |         0 | Hybride 277  |         | 
 259 |         0 | Hybride 278  |         | 
 260 |         0 | Hybride 279  |         | 
 261 |         0 | Hybride 280  |         | 
 262 |         0 | Hybride 281  |         | 
 263 |         0 | Hybride 282  |         | 
 264 |         0 | Hybride 283  |         | 
 265 |         0 | Hybride 284  |         | 
 266 |         0 | Hybride 285  |         | 
 267 |         0 | Hybride 286  |         | 
 271 |         0 | 24           |         | 
 272 |         0 | 33           |         | 
 273 |         0 | 794          |         | 
 274 |         0 | NC-9922      |         | 
 279 |         0 | sugar cane   |         | 
 280 |         0 | sugar cane   |         | 
(40 rows)

**Comment by dlebauer** [comment]
```sql
select distinct specie_id, cultivar_id from traits where cultivar_id in (select id from cultivars where specie_id not in (select id from species)) order by cultivar_id;
```

```sql
update cultivars set specie_id = 938 where id = 85 ;
update cultivars set specie_id = 2952 where id = 97 ;
update cultivars set specie_id = 1070 where id = 97 ;
update cultivars set specie_id = 2068 where id = 103 ;
update cultivars set specie_id = 2867 where id = 103 ;
update cultivars set specie_id = 2579 where id = 116 ;
update cultivars set specie_id = 2867 where id = 117 ;
update cultivars set specie_id = 2068 where id = 152 ;
update cultivars set specie_id = 2579 where id = 161 ;
update cultivars set specie_id = 2068 where id = 215 ;
update cultivars set specie_id = 2952 where id = 255 ;
update cultivars set specie_id = 2952 where id = 256 ;
update cultivars set specie_id = 2952 where id = 257 ;
update cultivars set specie_id = 2952 where id = 258 ;
update cultivars set specie_id = 2952 where id = 259 ;
update cultivars set specie_id = 2952 where id = 260 ;
update cultivars set specie_id = 2952 where id = 261 ;
update cultivars set specie_id = 2952 where id = 262 ;
update cultivars set specie_id = 2952 where id = 263 ;
update cultivars set specie_id = 2952 where id = 264 ;
update cultivars set specie_id = 2952 where id = 265 ;
update cultivars set specie_id = 2952 where id = 266 ;
update cultivars set specie_id = 2952 where id = 267 ;
update cultivars set specie_id = 2956 where id = 271 ;
update cultivars set specie_id = 2956 where id = 272 ;
update cultivars set specie_id = 2957 where id = 272 ;
update cultivars set specie_id = 2956 where id = 273 ;

update cultivars set specie_id = (select id from species where scientificname = 'Saccharum officinarum') where id in (279,280);
```

The rest of these cultivars are not referenced and thus I deleted them:

```sql
select count(*) from traits_and_yields_view_private where cultivar_id in (select id from cultivars where specie_id not in (select id from species));
select count(*) from cultivars_pfts where cultivar_id in (select id from cultivars where specie_id not in (select id from species));
delete from cultivars where id in (select id from cultivars where specie_id not in (select id from species))
```
