### ISSUE TITLE
inputs: missing users

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#168]
select id, user_id from inputs where user_id not in (select id from users);
 id  | user_id 
-----+---------
   6 |      -1
 204 |      -1
(2 rows)

Does "-1" have some special significance?

**Comment by dlebauer** [comment]
Not sure where the -1 came from, but the first is mine and the other belongs to @mdietze 

```sql
update inputs set user_id = 2 where id = 6
update inputs set user_id = 4 where id = 204
```
