### ISSUE TITLE
managements: missing citations

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#170]
select citation_id, count(*), array_agg(id) as ids_of_rows_referring_to_this_citation from managements where citation_id not in (select id from citations) group by citation_id order by citation_id;
 citation_id | count | ids_of_rows_referring_to_this_citation 
-------------+-------+----------------------------------------
         369 |     1 | {2400}
         484 |     3 | {3034,3035,3036}
(2 rows)

**Comment by dlebauer** [comment]
these managements are not associated with any treatments, so there is no way to track them down and they are probably orphaned.

```sql
delete from managements where id in (2400, 3034, 3035, 3036)
```
