### ISSUE TITLE
priors: missing variables

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#173]
select * from priors where variable_id not in (select id from variables);
 id  | citation_id | variable_id | phylogeny | distn | parama | paramb  | paramc | n |            notes             |     created_at   
   |     updated_at      
-----+-------------+-------------+-----------+-------+--------+---------+--------+---+------------------------------+------------------
---+---------------------
 209 |             |         458 | Trees     | unif  | 0.5000 | 15.0000 |        |   | Generic uninformative prior. | 2012-07-17 22:32:
03 | 2012-07-17 22:32:03
(1 row)

**Comment by dlebauer** [comment]
I don't use uniform priors, but there are no associated PFTs; I will delete this one.
