### ISSUE TITLE
sites: missing users

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#174]
Note this row has "DELETE ME" in the sitename column:

select * from sites where user_id not in (select id from users);
  id  |                                  city                                   | state  | country | mat | map | soil | som |          
                      notes                                | soilnotes |     created_at      |         updated_at         |    sitename
    | greenhouse | user_id | local_time | sand_pct | clay_pct |                              geometry                              
------+-------------------------------------------------------------------------+--------+---------+-----+-----+------+-----+----------
-----------------------------------------------------------+-----------+---------------------+----------------------------+------------
----+------------+---------+------------+----------+----------+--------------------------------------------------------------------
 1013 | Malmön Experimental Field Station for Short Rotation Forestry Research  | Köping |         |     |     |      |     | DELETE ME
; elevation queried from lat lon using R geonames::GNstrm3 |           | 2013-04-05 22:27:01 | 2014-08-20 12:25:23.877925 | more carl s
ite |            |      89 |            |          |          | 01010000A0E61000000000000000804D4000000000000030400000000000405440
(1 row)

**Comment by dlebauer** [comment]
```
delete from sites where id = 1013
```

**Comment by gsrohde** [comment]
This created another orphaned citations_sites row that didn't show up before.

```sql
select * from citations_sites where site_id not in (select id from sites);
 citation_id | site_id | created_at | updated_at 
-------------+---------+------------+------------
         178 |    1013 |            | 
(1 row)
```

**Comment by dlebauer** [comment]
delete from citations_sites where citation_id = 178 and site_id = 1013;
