### ISSUE TITLE
Remove counties and locations_yields tables

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#177]
* locations_yields
* counties
* sessions

The locations_yields and counties table are deprecated. It was originally created by @mulroony to support mapping of model output, but this approach has since been replaced.

The sessions table has never been used [Redmine 2048](https://ebi-forecast.igb.illinois.edu/redmine/issues/2048)

**Comment by gsrohde** [comment]
@dlebauer Regarding sessions:

Patrick's comment from March 21, 2012, when switching session_store.rb to store session information in the sessions table was 'Moving session key info from cookie to DB. Just better to do it this way'.

session_store.rb was switched back to using Cookie storage by Andrew's commit from January 22, 2013 (log message "Start Rails 3 upgrade").  I think this switch wasn't made on the production site until July 2013 (is this when we upgraded it to Rails 3?).

In any case, I now think we should keep the sessions table and switch back to using it.

**Comment by dlebauer** [comment]
@gsrohde Its your call, but it would be useful to know if there is any value to keeping this table around - beyond @mulroony's statement that it is "Just better". Does it affect functionality or reliability?

**Comment by gsrohde** [comment]
My guess is that Andrew took this out to get a Rails 3 version up and running fast, and he may even have intended the change to be temporary but then forgot about it.  Or it might even have been changed automatically by whatever scripts were run (if any) to facilitate the Rails version upgrade.

In any case--and I haven't delved into this very deeply--the little I have read suggests database storage is more secure than Cookie storage and it certainly allows for more to be stored in the session.  I haven't read of any down sides.

My immediate motivation for making the switch is to solve a problem with the bulk upload: the bulk upload stores in the session a list of all the different citations mentioned in the upload file.  This latest upload file is unusual in that it has a large set of different citations, and so the storage requirements exceed the capacity.  The easiest way to fix this is to switch from Cookie storage to database storage.

**Comment by gsrohde** [comment]
@dlebauer I think we should write a migration to delete the locations_yields table and the counties table and then close this.  Sound OK?

**Comment by dlebauer** [comment]
yes!

**Comment by gsrohde** [comment]
Removed in release 4.3
