### ISSUE TITLE
cultivars: (name, specie_id) should be a candidate key

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#182]
* [x] Eliminate or update rows with NULL names
* [x] Eliminate or update rows with NULL specie_id
* [x] Consolidate rows with matching (name, specie_id) values
* [x] Add not-NULL and uniqueness constraints - READY TO BE DONE
* [x] Normalize whitespace in the name column
* [x] Add whitespace normalization constraint - READY TO BE DONE
* [x] _Optional:_ Add a trigger function to automatically normalize name column values - READY TO BE DONE

* To find rows with NULL names:

```sql
SELECT * FROM cultivars WHERE name IS NULL;
```

(ebi_production currently has one such row, but there is another row with string value 'NULL' and 5 others where `name = ''`.)

* To find rows with NULL specie_id:

```sql
SELECT * FROM cultivars WHERE specie_id IS NULL;
```

* To find violations of the desired uniqueness constraint:

```sql
SELECT ARRAY_AGG(id), specie_id, name FROM cultivars GROUP BY specie_id, name HAVING COUNT(*) > 1;
```

(ebi_production currently has 27 groups duplicates, mostly pairs but also one group having 5 members.)

* To add the uniqueness and NOT NULL constraints:

```sql
ALTER TABLE cultivars ALTER COLUMN name SET NOT NULL;
ALTER TABLE cultivars ALTER COLUMN specie_id SET NOT NULL;
ALTER TABLE cultivars ADD CONSTRAINT unique_name_per_species UNIQUE (name, specie_id);
```

The uniqueness constraint will be more meaningful if we ensure that we don't allow multiple rows for a given species that differ only in the whitespace of the name column.

* To see unnormalized values, run

```sql
SELECT id, '@' || name || '@' AS name FROM cultivars WHERE name != REGEXP_REPLACE(TRIM(name), ' +', ' ');
```

(Surrounding the name string with '@' characters makes leading and trailing whitespace more apparent.)

* To normalize this column, run

```sql
UPDATE cultivars SET name = REGEXP_REPLACE(TRIM(name), ' +', ' ') WHERE name != REGEXP_REPLACE(TRIM(name), ' +', ' '); 
```

(The 'where' clause is not strictly necessary but doesn't hurt either.)

* Finally, to add the normalization constraint, run

```sql
ALTER TABLE cultivars ADD CONSTRAINT normalized_names CHECK (name = REGEXP_REPLACE(TRIM(name), ' +', ' ')); 
```

(We may want to write a function to make these types of check constraints easier to write so that we can just write `CHECK (name = normalize_whitespace(name))`, or even `CHECK (is_whitespace_normalized(name))`.)

* We could add a trigger function so that the name column value is automatically normalized upon insertion and update.

**Comment by dlebauer** [comment]
* fixed null values of cultivars.name
* fixed null values of specie_id
```sql
update cultivars set specie_id = 1478 where id = 81
update cultivars set specie_id = 2480 where id = 82
delete from cultivars where id in (290, 291, 295, 308, 358, 359, 360, 361, 369, 370)
update cultivars set specie_id = 33738 where id between 393 and 410
update cultivars set specie_id = 33738 where id = 451
update yields set cultivar_id = NULL where specie_id in (1067, 1072) and cultivar_id = 451
```
