### ISSUE TITLE
formats: make dataformat a key

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#184]
* [ ] Add not-NULL constraint to dataformat column
* [ ] Eliminate duplicate dataformat values
* [ ] Add uniqueness constraint to dataformat column
* [ ] Consider adding value constraint to dataformat column
* [ ] Consider adding uniqueness constraints to other columns

# Not-NULL constraint

There are no rows with NULL in this column so we can already add

```sql
ALTER TABLE formats ALTER COLUMN dataformat SET NOT NULL;
```

# Duplicate dataformat values

The duplicates all have the empty string as the value of dataformat:

```sql
SELECT ARRAY_AGG(id), LENGTH(dataformat), dataformat FROM formats GROUP BY dataformat HAVING COUNT(*) > 1;
                   array_agg                    | length | dataformat 
------------------------------------------------+--------+------------
 {17,18,16,29,33,35,36,37,39,38,41,42,43,44,45} |      0 | 
(1 row)
```

If this isn't an error, then we need to reconsider whether `dataformat` is really a key.

# Uniqueness

```sql
ALTER TABLE formats ADD CONSTRAINT unique_data_format UNIQUE (dataformat);
```

# Value constraints

It seems like most dataformat values consist of one or more SQML-style tags, sometime separated by Windows-style line-break sequences ('\r\n').  But at least three values look like complete XML documents.  I don't know exactly how this column is used, but it seems like there is room for some standardization.

# Additional uniqueness constraints

The `name` column is currently unique and so it seems that it also could serve as a candidate key.

**Comment by mdietze** [comment]
The dataformat column has been deprecated. Don't make it a key. We should create an issue to migrate the legacy information in that table into the formats_variables relationships and then drop the column in a fairly soon release.

**Comment by mdietze** [comment]
The issue to drop formats.dataformat is #336.
