### ISSUE TITLE
posteriors: make (pft_id, format_id) a key

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#198]
* ~~[ ] Assign each row a format_id~~
* [x] Delete existing rows (and dependents)
* [x] Add not NULL constraints
* [ ] Add uniqueness constraint

# Existing nulls.

Currently, all rows have null format_id;

# Adding not NULL constraints

```sql
ALTER TABLE posteriors ALTER COLUMN pft_id SET NOT NULL;
```

~~ALTER TABLE posteriors ALTER COLUMN format_id SET NOT NULL;~~

# Uniqueness

The uniqueness constraint is:
~~ALTER TABLE posteriors ADD CONSTRAINT unique_format_per_pft UNIQUE (pft_id, format_id);~~

This is currently satisfied, but only because format_id is always NULL.

**Comment by dlebauer** [comment]
@gsrohde you can delete all existing rows from this table and apply the constraints

**Comment by dlebauer** [comment]
the `posteriors.format_id` column should be removed

**Comment by dlebauer** [comment]
I can't think of a reasonable uniqueness constraint for the posteriors that doesn't require a cross-table lookup of dbfiles.

**Comment by gsrohde** [comment]
@dlebauer If no Uniqueness constraint is warranted, close this.
