### ISSUE TITLE
species: design a strategy for eliminating duplicates

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#202]

**Comment by gsrohde** [comment]
@dlebauer 

The script /informational queries/species_cleanup/xsltproc.sh in the bety-qaqc github repository should do most of the work.

Run it with the -i option to see how to use it.  (Let me know if the instructions are clear enough.)

Try it out on a test copy first.  Then we can talk about moving forward with it.

**Comment by dlebauer** [comment]
This seems to have worked!
