### ISSUE TITLE
Create API key for users

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#203]
* [x] generate api keys for existing users
* [x] show api key on users/show page
* [x] generate api key when new account is created
* [x] add key to email sent for new accounts

There is an apikey field in the users table, but only a few accounts have keys.

**Comment by dlebauer** [comment]
can be closed after deploying #229

**Comment by gsrohde** [comment]
Not really done—I haven’t merged pull request #229 let alone deployed it.  But I’ll work on merging it now.

**Comment by dlebauer** [comment]
deployed in BETYdb 4.0
