### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#207]
Please describe how the following operations can be performed in the API:
* join tables (across one to many and across many to many, e.g. via `managements_treatments`)
* subset rows `where x in ( ...)`
* subset columns `select colA, colB, ... from table ...`
* select distinct values (or count distinct values as in : `select scientificname, count(*) as n from traits_and_yieldsview group by scientificname, order by n` 
* limit the number of records returned `limit <n>`

I suspect that this is taken care of by some intelligent ruby and/or rails magic, but it is not clear. Perhaps there is a specific Ruby gem or method / function we are using that would explain the general case?

**Comment by dlebauer** [comment]
Example queries from PEcAn, 

Note that we don't _necessarily_ want to be exposing users to foreign keys, this is how we do it in PEcAn

```sql

   SELECT pfts.id FROM pfts, modeltypes WHERE pfts.name='salix' and 
   pfts.modeltype_id=modeltypes.id and modeltypes.name='BIOCRO' 

   select species.id, species.genus, species.species, species.scientificname 
   from species, pfts, pfts_species, modeltypes where 
   species.id=pfts_species.specie_id and pfts.id=pfts_species.pft_id and 
   pfts.name='salix' and pfts.modeltype_id=modeltypes.id and 
   modeltypes.name='BIOCRO' 


   select traits.id, traits.citation_id, traits.site_id, traits.treatment_id, 
   treatments.name, traits.date, traits.time, traits.cultivar_id, 
   traits.specie_id, traits.mean, traits.statname, traits.stat, traits.n, 
   variables.name as vname, extract(month from traits.date) as 
   month,ST_X(ST_CENTROID(sites.geometry)) AS lon, 
   ST_Y(ST_CENTROID(sites.geometry)) AS lat, treatments.control, 
   sites.greenhouse from traits left join treatments on (traits.treatment_id = 
   treatments.id) left join sites on (traits.site_id = sites.id) left join 
   variables on (traits.variable_id = variables.id) where specie_id in 
   ('1243','36606','2583','50922','2869','36702','2870','2872','2878','51120','35796','51193') 
   and variables.name in ('cuticular_cond'); 


   select covariates.trait_id, covariates.level,variables.name from covariates 
   left join variables on variables.id = covariates.variable_id where trait_id 
   in ('51247','51249','51251','51253','51255','51257','51281','51283','51285','51287','51307','51309','51311','51313','51315','51317','51319','51321','51323','51325','51289','51291','51293','51295','51297','51299','51301','51303','51305' 
   ) 
```

**Comment by gsrohde** [comment]
@dlebauer I've drafted updates to the API documentation (https://www.authorea.com/users/5574/articles/7062/_show_article#2).  I put major changes in boldface (except where I couldn't--namely the sample queries) pending firming everything up and also so you can see what has changed.

All the queries in that document now work (try them out on pecandev)--some with no changes, others with minor changes to the syntax.  The query you show immediately above is significantly more complicated, and I will have to see how this can be done or what changes need to be made to make it possible to do.

**Comment by gsrohde** [comment]
UPDATE:

To answer the questions posed in the original issue text:

1. Tables can currently only be joined if they are specified as associations in the corresponding Rails models (via "has_one", "has_many", "belongs_to", etc.).  Moreover, there is some limit what we can do in the "where" clause if a table is only indirectly associated. (I'll say more about this later.)
2. `where x in (...)` can be done, although a bit awkwardly.  For example, to find sites `where city in ('Corvallis', 'Urbana')` we can do `www.betydb.org/sites.xml?city[]=Corvallis&city[]=Urbana`.
3. When working with a single table, we can choose only to show some given list of columns using the `filters[]=` syntax.  For example, to display only the

**Comment by dlebauer** [comment]
@gsrohde what is the status of this? When will it be deployed / working on betydb.org?

**Comment by gsrohde** [comment]
As I said in my previous comment, all the queries in the existing API document already work, but in some cases I had to update that document to correct the syntax required to execute the queries.

I didn't pull Yilin's request #260 for three reasons: I wasn't sure it was needed now that I have shown how to do all the queries listed in the current API document; the API for using her additions seemed somewhat awkward; and finally, she hasn't yet written up with the documentation for using it.  (I see that this issue was originally assigned to her, but there have been no comments from her on it.)

Is there anything in particular that you want to be able to do through the API that isn't now possible?  It does seem that in spite of the fact that all the examples mentioned in the current API document are already possible, some of the examples you mention the original comment for this issue are not.  If feel these are important, then we can decide how best to proceed.

**Comment by dlebauer** [comment]
This was per @phenolphtalein's comment that the queries weren't working. Yilin - could you please check the documentation again, and if any of the queries don't work, please open a separate issue?

**Comment by phenolphtalein** [comment]
The reason I used the join method for api_search is that I never got "include" to work properly. In the screenshot below I pasted the exact same url from the documentation (except that I'm using my local copy of the database), but the include doesn't seem to do anything and it's still returning all the yields...
![screen shot 2015-04-06 at 10 18 05 am](https://cloud.githubusercontent.com/assets/7217695/7006430/b60ef26c-dc46-11e4-9879-11dd3b800221.png)
@gsrohde Does this work as expected on the production web interface?

**Comment by gsrohde** [comment]
@dlebauer @phenolphtalein 

Sorry--my comment from the 1st was misleading.

The queries I mentioned are working in the lastest version of BETYdb master, but that code hasn't been deployed to betydb.org yet.  (My comment from March 20th says to try the queries on pecandev, but later comments of mine make it sound like they already work on the live site.  I think these queries _may_ have worked on the live site before we upgraded from Rails 2 to Rails 3 (with possibly slightly different syntax) but they quit working once we upgraded to Rails 3 over a year and a half ago.)

I hope to release a new version of BETYdb this week, but in the mean time, you can try the queries on the beta site, https://ebi-forecast.igb.illinois.edu/beta.

**Comment by dlebauer** [comment]
@phenolphtalein please confirm that the new documentation is correct and let me know if I can close this.

**Comment by gsrohde** [comment]
@dlebauer @phenolphtalein  

I just updated the whole of the Data Access document (https://www.authorea.com/users/5574/articles/7062/_show_article) and I think it is now reasonably accurate and up-to-date, so I am closing this issue.
