### ISSUE TITLE
Automatically query covariates associated with a given trait

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#208]
When traits are selected, appropriate covariates should also be returned. For example, kinetic rates need a temperature covariate. 

@gsrohde where is the table of variable <--> covariate pairs that you used to implement the checks in the bulk uploads?

**Comment by gsrohde** [comment]
The table is `trait_covariate_associates`.  FYI, as I mentioned earlier, the Rails app has view access to it but no way to change it.

**Comment by dlebauer** [comment]
need to add `betydb_covariates` function to the ropensci/traits package

**Comment by dlebauer** [comment]
enabled in dlebauer/traits#1
