### ISSUE TITLE
All created_at and updated_at columns should default to NOW()

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#214]
* [x] Consider (and comment on) proposed change
* [ ] Implement default (and possible not NULL constraint)

Although these columns will get set properly (I think) when an insertion happens via the Rails interface, there is no harm that I can see in making this a default at the database level.  Too often these columns are NULL.

We might consider requiring them to be non-NULL.  This would entail updating all existing NULLs to some default, for example Julian Date 0 ('J0').

**Comment by robkooper** [comment]
sure sounds great.

**Comment by gsrohde** [comment]
Since Rails uses "timestamp without time zone" for its timestamp columns (created_at and updated_at) and then just always stores UTC times, we have to do the same, so the defaults need to be
```sql
NOW() at time zone 'UTC'
```
