### ISSUE TITLE
citations_treatments: Finish making key

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#215]
* [x] Update or delete row with NULL citation_id.
* [x] Add not NULL constraints

`(citation_id, treatment_id)` is constrained to be unique, but the constituent columns should be constrained to be non-NULL.

In fact, `citation_id` is NULL in one row.

The constraints to add are
```sql
ALTER TABLE citations_treatments ALTER COLUMN citation_id SET NOT NULL;
ALTER TABLE citations_treatments ALTER COLUMN treatment_id SET NOT NULL;
```

**Comment by dlebauer** [comment]
The null citation_id was a duplicate

```sql
update traits set citation_id = 95, updated_at = now() where id = 24459;
delete from citations_treatments where citation_id is null and treatment_id = 230
```
