### ISSUE TITLE
Issues installing postGIS with postGRES 9.4

### ISSUE THREAD

**Issue by Viskari** [PecanProject/bety#228]
We are currently having difficulties getting all the libraries required by PEcAn installed on to our server, with one of the current issues being the postGIS and Raster libraries. Attached is the error message we are getting. Another little oddity in it is that even though we have the newer postgres version 9.4 installed, during installation it continues to refer to the 9.3.5 version. Below is the error log.

Any help would be appreciated.

[Error log]:

  It was created by configure, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --with-pgconfig=/usr/pgsql-9.4/bin/pg_config --with-projdir=/data/software/proj/4.8.0 --with-jsondir=/data/software/json-c/0.12 --with-gdalconfig=/data/software/gdal/1.11/bin/gdal-config --with-geosconfig=/data/software/geos/3.4.2/bin/geos-config --with-xml2config=/data/software/libxml2/2.9.1/bin/xml2-config --with-gui --with-raster --with-topology

## --------- ##

hostname = test
uname -m = x86_64
uname -r = 2.6.32-504.8.1.el6.x86_64
uname -s = Linux
uname -v = #1 SMP Tue Jan 27 13:39:10 CST 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /data/software/proj/4.8.0/bin
PATH: /software/mpi/openmpi/1.6.4-gnu48/bin
PATH: /software/gcc-4.8.0/include
PATH: /software/gcc-4.8.0
PATH: /software/gcc-4.8.0/bin
PATH: /data/software/jags/jags-3.4.0/bin
PATH: /data/software/laszip/2.2.0/bin
PATH: /data/software/src/gdal/gdal-1.11/gdal/swig/python/scripts
PATH: /data/software/gdal/1.11/bin
PATH: /data/software/netcdf/4.3.3rc2/bin
PATH: /data/software/hdf5/1.8.13/bin
PATH: /data/software/hdf4/4.2.10/bin
PATH: /data/software/geotiff/1.4.1/bin
PATH: /data/software/libtiff/4.0.3/bin
PATH: /usr/lib64/qt-3.3/bin
PATH: /usr/local/bin
PATH: /bin
PATH: /usr/bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /sbin
PATH: /home0/sserbin/bin
  
  
  
  PostGIS is now configured for x86_64-unknown-linux-gnu

 -------------- Compiler Info ------------- 
  C compiler:           mpicc -g -O2
  C++ compiler:         mpiCC -g -O2
  SQL preprocessor:     /software/gcc-4.8.0/bin/cpp -w -traditional-cpp -P

 -------------- Dependencies -------------- 
  GEOS config:          /data/software/geos/3.4.2/bin/geos-config
  GEOS version:         3.4.2
  GDAL config:          /data/software/gdal/1.11/bin/gdal-config
  GDAL version:         1.11.0
  PostgreSQL config:    /usr/pgsql-9.4/bin/pg_config
  PostgreSQL version:   PostgreSQL 9.4.0
  PROJ4 version:        48
  Libxml2 config:       /data/software/libxml2/2.9.1/bin/xml2-config
  Libxml2 version:      2.9.1
  JSON-C support:       yes
  PostGIS debug level:  0
  Perl:                 /usr/bin/perl

 --------------- Extensions --------------- 
  PostGIS Raster:       enabled
  PostGIS Topology:     enabled
  SFCGAL support:       disabled

 -------- Documentation Generation -------- 
  xsltproc:             /usr/bin/xsltproc
  xsl style sheets:     /usr/share/sgml/docbook/xsl-stylesheets
  dblatex:              
  convert:              /usr/bin/convert
  mathml2.dtd:          http://www.w3.org/Math/DTD/mathml2/mathml2.dtd
  
  
  ...
  
  make[2]: Entering directory `/data/software/src/postgis/postgis-2.1.5/raster/loader'
mpicc -g -O2  -fPIC -DPIC  -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom -I/data/software/proj/4.8.0/include -I/data/software/gdal/1.11/include -I/data/software/geos/3.4.2/include   -c raster2pgsql.c
/bin/sh ../../libtool --mode=link mpicc -g -O2  -fPIC -DPIC  -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom -I/data/software/proj/4.8.0/include -I/data/software/gdal/1.11/include -I/data/software/geos/3.4.2/include   ../rt_core/librtcore.a raster2pgsql.o ../../liblwgeom/liblwgeom.la -L/data/software/gdal/1.11/lib -lgdal  -L/data/software/geos/3.4.2/lib -lgeos_c  -lc -lm -o raster2pgsql
libtool: link: mpicc -g -O2 -fPIC -DPIC -Wall -Wmissing-prototypes -I../rt_core -I../../liblwgeom -I/data/software/proj/4.8.0/include -I/data/software/gdal/1.11/include -I/data/software/geos/3.4.2/include raster2pgsql.o -o .libs/raster2pgsql  ../rt_core/librtcore.a ../../liblwgeom/.libs/liblwgeom.so -L/data/software/geos/3.4.2/lib -L/data/software/proj/4.8.0/lib -L/data/software/json-c/0.12/lib /data/software/proj/4.8.0/lib/libproj.so /data/software/json-c/0.12/lib/libjson-c.so -L/data/software/gdal/1.11/lib /data/software/gdal/1.11/lib/libgdal.so -L/usr/lib -L/data/software/postgresql/9.3.5/lib -L/data/software/libxml2/2.9.1/lib -lsqlite3 -lodbc -lodbcinst -lexpat -lxerces-c -lnetcdf -lhdf5 -ljpeg -lpng -lpq -lpthread -lrt -lpcre -lcurl /data/software/libxml2/2.9.1/lib/libxml2.so -llzma -lz -ldl /data/software/geos/3.4.2/lib/libgeos_c.so /data/software/geos/3.4.2/lib/libgeos.so -lc -lm -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/data/software/proj/4.8.0/lib -Wl,-rpath -Wl,/data/software/json-c/0.12/lib -Wl,-rpath -Wl,/data/software/gdal/1.11/lib -Wl,-rpath -Wl,/data/software/libxml2/2.9.1/lib -Wl,-rpath -Wl,/data/software/geos/3.4.2/lib
/usr/bin/ld: warning: libhdf5.so.8, needed by /data/software/gdal/1.11/lib/libgdal.so, may conflict with libhdf5.so.7
/data/software/gdal/1.11/lib/libgdal.so: undefined reference to `nc_inq_var_chunking'
/data/software/gdal/1.11/lib/libgdal.so: undefined reference to `nc_def_var_chunking'
/data/software/gdal/1.11/lib/libgdal.so: undefined reference to `nc_def_var_deflate'
collect2: error: ld returned 1 exit status
make[2]: *** [raster2pgsql] Error 1
make[2]: Leaving directory `/data/software/src/postgis/postgis-2.1.5/raster/loader'
make[1]: *** [rtloader] Error 2
make[1]: Leaving directory `/data/software/src/postgis/postgis-2.1.5/raster'
make: *** [all] Error 1

**Comment by Viskari** [comment]
A few further details on the issue:

We are trying to install it with the command:
 ./configure --with-pgconfig=/usr/pgsql-9.4/bin/pg_config --with-projdir=/data/software/proj/4.8.0 --with-jsondir=/data/software/json-c/0.12 --with-gdalconfig=/data/software/gdal/1.11/bin/gdal-config --with-geosconfig=/data/software/geos/3.4.2/bin/geos-config --with-xml2config=/data/software/libxml2/2.9.1/bin/xml2-config --with-gui --with-raster --with-topology

And the paths and flags defined in pgconfig are:

BINDIR = /usr/pgsql-9.4/bin
DOCDIR = /usr/share/doc/pgsql
HTMLDIR = /usr/share/doc/pgsql
INCLUDEDIR = /usr/pgsql-9.4/include
PKGINCLUDEDIR = /usr/pgsql-9.4/include
INCLUDEDIR-SERVER = /usr/pgsql-9.4/include/server
LIBDIR = /usr/pgsql-9.4/lib
PKGLIBDIR = /usr/pgsql-9.4/lib
LOCALEDIR = /usr/pgsql-9.4/share/locale
MANDIR = /usr/pgsql-9.4/share/man
SHAREDIR = /usr/pgsql-9.4/share
SYSCONFDIR = /etc/sysconfig/pgsql
PGXS = /usr/pgsql-9.4/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--disable-rpath' '--prefix=/usr/pgsql-9.4' '--includedir=/usr/pgsql-9.4/include' '--mandir=/usr/pgsql-9.4/share/man' '--datadir=/usr/pgsql-9.4/share' '--with-perl' '--with-python' '--with-tcl' '--with-tclconfig=/usr/lib64' '--with-openssl' '--with-pam' '--with-gssapi' '--with-includes=/usr/include' '--with-libraries=/usr/lib64' '--enable-nls' '--with-uuid=e2fs' '--with-libxml' '--with-libxslt' '--with-ldap' '--with-system-tzdata=/usr/share/zoneinfo' '--sysconfdir=/etc/sysconfig/pgsql' '--docdir=/usr/share/doc' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et' 'CPPFLAGS= -I/usr/include/et'
CC = gcc
CPPFLAGS = -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2 -I/usr/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et
CFLAGS_SL = -fpic
LDFLAGS = -L../../../src/common -L/usr/lib64 -Wl,--as-needed
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lrt -lcrypt -ldl -lm

**Comment by dlebauer** [comment]
@Viskari do you by chance remember how this was resolved? Installing PostGIS has been a continual source of trouble, and I often find myself referring to old [issues](https://github.com/PecanProject/bety/issues?utf8=✓&q=is%3Aissue+postgis+) for solutions.

**Comment by Viskari** [comment]
We essentially had to drop a lot of the flags from the configure command. We have the commands we used in notes, I'll try to post them on Monday.
