### ISSUE TITLE
covariates value constraints: needed cleanup and decisions

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#231]
#### level
- [ ] Analyze instances where this is NULL and see if cleanup is required and whether constraints are warranted.  See issue #267.
#### n
- [x] Decide if n can be 1; change 1's to NULL if not.
  - n can be 1 
- [ ] Add CHECK (n >= 1)
#### stat, statname, n consistency
- [x] Decide on consistency constraints
- [x] Fix cases where stat is not null but no statname is given (17 rows) -- see issue #268
- [ ] Add needed constraints
# Details
## n

n = 1 in 18 cases; in these cases stat is NULL and statname = ''.

There is one case where n = 0.  See discussion in consistency section.
## consistency

We then will normally expect either of the following to hold for a given row:
1. ~~n > 1, stat is not null, and statname is specified (that is, not equal to '')~~
2. ~~n is NULL, stat is NULL, and statname is not specified (that is, equals '')~~

Not all existing data conforms to these expectations, however.  This begs certain questions:
1. Should n = 1 be allowed?  If so, do stat and statname have meaning in this case, or should they be required to be NULL and the empty string respectively?
   - **yes**
2. Should n = 0 be allowed?  If it is allowed, then it must be assigned some special meaning since a value for level does not make sense otherwise.
   - **no**
3. If n > 1, should it be required that a stat be given and a statname be specified?  (Is there any point to giving n otherwise?  Perhaps yes.)
   - **no**  sample size provies useful information even if statistic is not available (or, e.g., something vague like P is supplied)
4. Should it ever be allowable to specify a sample size and a stat value without specifying the statname?
   - ~~**yes**~~ no
5. If a stat is given and a statname is specified, is it permissible to have n be NULL?
   - **yes**

A negative answer to any of these means some rows will have to be corrected or deleted.
### More Details

``` sql
SELECT * FROM  covariates WHERE NOT (statname = '' AND stat IS NULL OR statname != '' AND stat IS NOT NULL);
```

shows 17 rows with a stat but no statname.  We have to decide how to handle this.  In one of these, n = 0: If this is used as a special marker, there should be a comment to that effect; if not, this row should be fixed or deleted.

There are no rows where statname is given but stat is NULL.

``` sql
SELECT * FROM covariates WHERE stat IS NOT NULL AND statname != '' AND n IS NULL;
```

shows 106 rows where statistics are given but n is NULL.

``` sql
SELECT *  FROM covariates WHERE stat IS NULL AND n IS NOT NULL;
```

shows 29 rows where n is given but stat is not.  In 18 of these n = 1, but in the remaining 11, n is greater than 1.

**Comment by dlebauer** [comment]
in general, all of these fields should be handled the same way as they are handled in the traits and yields table (where level here is analogous to mean in the other tables)

**Comment by dlebauer** [comment]
Issue moved to [PecanProject/bety-data #1](https://github.com/PecanProject/bety-data/issues/1) via [**ZenHub**](https://www.zenhub.com/)
