### ISSUE TITLE
dbfiles value constraints: needed cleanup and decisions

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#233]
* [x] Decide on constraints for file_name, file_path, and container_id
* [x] Add to new migration

See dbfiles in secion 3 of https://www.overleaf.com/2086241dwjyrd#/5297403/.

**Comment by gsrohde** [comment]
Only remaining constraints (which will be implemented by draft value constraint migration) are on the values of `md5` and `container_type`.

**Comment by dlebauer** [comment]
can `md5` and `container_type` both have defaults of either NULL or empty string?

**Comment by gsrohde** [comment]
The migration `value_constraints_batch_1` was included in release 4.2. This ensures `dbfiles.md` is either NULL, the empty string, or is a 32-character string of digits and/or lower-case latin letters.  It ensures `dbfiles.container_type` is either NULL or one of 'Model', 'Posterior', or 'Input'.  NULL is the default value for both columns.
