### ISSUE TITLE
priors value constraints: needed cleanup and decisions

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#243]
#### phylogeny
* [x] Decide if a more restrictive value constraint than is_whitespace_normalized can be used
 * not needed this is for human-readability. Would be nice to have standardized capitalization (e.g. 'plants', but not necessary. [See comment below.]
* [x] If so, add it to migration--WILL GO WITH ONLY WHITESPACE NORMALIZATION FOR NOW

#### distn
* [x] Constrain to a finite set of predetermined values (see Rails select dropdown) and NOT NULL

#### parama, paramb, paramc
* [x] Decide if some value constraint(s) make sense
 * no, except that these are numeric. _And parama should not be NULL._
* [x] If so, add it (them)

#### n
* [x] Decide what constraints, if any, to use
 * >= 0; default 0.
 * parama not null
* [ ] Add them if required

# Details

## phylogeny

There seem to be many near duplicates.  For example, "C3", "C3 Grass", "C3 plants", and "C3 Plants" all occur.

## parama, paramb, paramc

It seems like some kind of range constraint based on the value of distn should be possible.
 * could be looked up for each distribution, but this is not necessary - these values will be checked when they are used.

Currently parama is always non-NULL.  If this will always be the case, we can add a NOT NULL constraint to this column.

# n

See discussion of n in other tables (covariates, traits, yields) and in https://www.overleaf.com/2086241dwjyrd#/5297403/.

**Comment by gsrohde** [comment]
@dlebauer So I've got:

* n >= 0
* parama NOT NULL

Can n be NULL?  It is often NULL now.

We could enforce lower case on phylogeny.  Is it worthwhile?

**Comment by gsrohde** [comment]
The phylogeny column is also part of a proposed key, so it would be preferable not to have two entries that differ only in capitalization. For now, I've simply updated the database to put everything in lower case except terms like "C3", "C4", "CAM", and "PAVI2", but I haven't implemented any constraint that will prevent these "duplicates" from occurring in the future. It would also be good to consolidate singular and plural--entries like "C4 grass" vs. "C4 grasses".

**Comment by gsrohde** [comment]
What does it mean for n to be zero?

**Comment by dlebauer** [comment]
sorry, n>o

**Comment by gsrohde** [comment]
@dlebauer If `n` should be _greater_ than 0, what should be done with the 50 existing rows where `n` _equals_ 0?

**Comment by dlebauer** [comment]
Change constraint to n>= 0, to allow for prior so based on 'expert knowledge'

**Comment by gsrohde** [comment]
@dlebauer I'll also allow `n` to be NULL unless you don't want this and tell me how to handle the 80 rows that currently have NULL in the `n` column.

**Comment by dlebauer** [comment]
N can be 0 where it is currently NULL

**Comment by gsrohde** [comment]
The migration `value_constraints_batch_1` was included in release 4.2. This ensures:
* `priors.variable_id` is not null
* `priors.phylogeny` is not null and is whitespace-normalized
* `priors.distn` is not null and is one of 'beta', 'binom', 'cauchy', 'chisq', 'exp', 'f', 'gamma', 'geom', 'hyper', 'lnorm', 'logis', 'nbinom', 'norm', 'pois', 't', 'unif', 'weibull', or 'wilcox'
* `priors.parama` is not null
* `priors.n` is non-negative (if it isn't null)
