### ISSUE TITLE
runs value constraints: needed cleanup and decisions

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#245]
- [x] Decide what constraints are possible
- [ ] Decide on precise form of started_at constraint (pending resolution of #257) [Resolved for now by assuming local machine time; see note]
- [ ] Add them.
# Details

At the least, all textual columns will be set to NOT NULL.

**Comment by dlebauer** [comment]
make sure to look at not-null value constraints defined in the [google spreadsheet](https://docs.google.com/spreadsheets/d/1fJgaOSR0egq5azYPCP0VRIWw1AazND0OCduyjONH9Wk/edit#gid=702736141).

At least, all *id fields are integers, all times are ... times. created_at, updated_at should be > 2010-01-01; etc.

**Comment by gsrohde** [comment]
You don't need to mention constraints that are already inherent in the data types being used ("all *id fields are integers").  That said, there may be cases where the _wrong_ data type has been used.  (For example, variables.min and variables.max are varchar, not numeric.)

**Comment by gsrohde** [comment]
The NOT NULL constraints for the non-textual columns were dealt with in GH issue #200.  The one exception (of the NOT-NULL constraints specified in the google spreadsheet) is the column `started_at`.  So I've added a non-NULL constraint for it to my draft migration and also specified it to be <= NOW().

**Comment by gsrohde** [comment]
While created_at and updated_at are always UTC (or should be), the comments on started_at and finished_at refer to 'machine time'.  Thus, we'll assume the constraint should be `started_at <= NOW()::timestamp` where the explicit cast to timestamp, while not necessary, makes clear we are comparing `started_at` with the current local or machine time.

**Comment by gsrohde** [comment]
@dlebauer All the runs created in March and April have a NULL in the `started_at` column.  Is this an error, or should we forget about having a not-NULL constraint on this column?

**Comment by dlebauer** [comment]
Delete these rows, add constraint, and then we will fix pecan

**Comment by gsrohde** [comment]
The migration `value_constraints_batch_1` was included in release 4.2. This ensures that `runs.outdir`, `runs.outprefix`, and `runs.setting` are all non-null and have a default value of `''`.

**Comment by gsrohde** [comment]
@dlebauer See pending (unchecked) item above and decide whether to ignore, table (put in backlog), or fix now.

**Comment by dlebauer** [comment]
@gsrohde it looks like this constraint is ready to be added. Is that correct?

**Comment by gsrohde** [comment]
@dlebauer Remaining to do (or not) are value constraints on the columns of type timestamp—namely `start_time`, `finish_time`, `started_at`, and `finished_at`.  Here are constraints that I wanted to add to a previous migration but had to comment out because existing data violates them:
```sql
-- ALTER TABLE runs ALTER COLUMN started_at SET NOT NULL;
-- ALTER TABLE runs ADD CONSTRAINT valid_run_start_time CHECK (started_at <= NOW()::timestamp); -- NOW()::timestamp makes clear we are using local machine time
-- ALTER TABLE runs ADD CONSTRAINT consistent_run_start_and_end_times CHECK (started_at <= finished_at AND finished_at <= NOW()::timestamp);
```
As an example, on ebi_production, running
```sql
select * from runs where not started_at <= finished_at;
```
returns 7 rows, 4 of which were created in the last two weeks.

Another issue is what timezone is being assumed for these times.  For existing data, in some cases it seems to be Illinois time and in other cases it seems to be UTC.  Perhaps this is not important.

**Comment by dlebauer** [comment]
@robkooper @mdietze can you address Scott's questions above?

**Comment by mdietze** [comment]
Time zone is critical if you put any constraints on started_at and finished_at otherwise this will completely destroy the sync system. All times should be UTC. We decided that a few years ago so hopefully any Central time records are old.   There should be no constraints on the absolute values of start_time and finish_time. The relative constraint of finish being after start seems ok

**Comment by dlebauer** [comment]
Issue moved to [PecanProject/bety-data #5](https://github.com/PecanProject/bety-data/issues/5) via [**ZenHub**](https://www.zenhub.com/)
