### ISSUE TITLE
Bulk upload should not insert NULL in textual columns

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#262]
Where possible, the bulk upload should insert the empty string '' when data is missing for a column.

This may be solved by setting default values for these columns at the database level.

**Comment by dlebauer** [comment]
Are there any columns that will have a default of NULL? Or will this not be
an issue after the value constraints are set?

**Comment by gsrohde** [comment]
In the four tables that the bulk upload touches, there are only a very few columns with textual type--namely, `statname` and `notes` in the traits and yields tables, `statname` in the covariates table, and `name` and `notes` in the entities table.  These should, I think, default to the empty string.

Any column that doesn't explicitly set a default automatically defaults to NULL.  (This means columns set to NOT NULL must always be set explicitly in INSERT statements unless some non-null default has been set.)

Most likely, any column that continues to allow NULL in place of a bona fide value will keep NULL as the default: If there were some other reasonable default value, it is likely that NULL wouldn't serve any useful purpose.

**Comment by gsrohde** [comment]
Placing on hold until database design issues are resolved.

**Comment by gsrohde** [comment]
Pretty sure this is not an issue.
