### ISSUE TITLE
Species with missing scientificname, genus, species, and commonname

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#269]
There are 19 species records that have no scientificname, genus, species, or commonname. All are associated with citation_id 199 (Xiaohui Feng, field data).

Some are apparently plant communities. A few appear to be specific species, and four have no information. 

For communities please give a descriiption that we can put in the commonname field (similar to how the USDA plants database has entries for plant types ("Tree", "Subshrub") or at least the name of a specific community.

Notably, all of these records are for `c2n_[root, leaf, stem]` or `seedling_mortality`; none are associated with a particular site, and although they were collected pre 2000, all have `checked = -1` are not associated with their original citation. One option would be to delete these. 

These were discussed three years ago in [Redmine 737](https://ebi-forecast.igb.illinois.edu/redmine/issues/737).

Presumably "PFTs" would be a better place for such community level definitions, but is beyond the scope of what we can do presently with the database. 

``` sql
select id, AcceptedSymbol from traits join species on traits.specie_id = species.id 
        where scientificname = '' and commonname = '' ;
```

| id | AcceptedSymbol |
| :-: | :-: |
| 2925 | prairiemix4woody |
| 2932 | SORI2 |
| 2922 | prairiemix4forb |
| 2888 | POBA |
| 2892 | POMATRI |
| 2895 | POEU |
| 2899 | prairiemix6 |
| 2902 | HEGR4*HEMA2 |
| 2904 | ASLA5 |
| 2905 | ASOO4 |
| 2910 | DESM |
| 2911 | ECHI |
| 51169 |  |
| 2921 | Prairemix2-11 |
| 51106 |  |
| 51107 |  |
| 51111 |  |
| 2923 | prairiemix4grass |
| 2924 | prairiemix4legu |

(19 rows)

**Comment by mdietze** [comment]
This should be assigned to Sunny since it's her data

**Comment by dlebauer** [comment]
Does she have a github account?

**Comment by mdietze** [comment]
@lovelilyinfall

**Comment by lovelilyinfall** [comment]
These data are not my field data collected from EBI farm. EBI farm did not have these species planted. In addition, all my data from EBI farm are on species level. I have looked but not found the literature for these data. I think you can delete them.

**Comment by dlebauer** [comment]
Issue moved to [PecanProject/bety-data #8](https://github.com/PecanProject/bety-data/issues/8) via [**ZenHub**](https://www.zenhub.com/)
