### ISSUE TITLE
Poplar Data: Multiple Errors in BETYdb

### ISSUE THREAD

**Issue by echeng7** [PecanProject/bety#272]
Hello! 

I have come across the same problem throughout all the Poplar citations. Many of the yields have been associated to a combination of wrong sites, cultivars, treatments, and species.  

Example: 
![uploads/43213296-b5d7-4938-bb5b-ad90f41e6ebb/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F43213296-b5d7-4938-bb5b-ad90f41e6ebb%2Fblob)

In this situation, all the cultivars are wrong, as well as some of the treatments and the site is not associated at all, even though there are sites linked to the citation. 

While I have been updating them manually, it is probably a good idea to look into it to see if it is more widespread through the system. Thanks! @dlebauer

**Comment by dlebauer** [comment]
Issue moved to [PecanProject/bety-data #9](https://github.com/PecanProject/bety-data/issues/9) via [**ZenHub**](https://www.zenhub.com/)
