### ISSUE TITLE
Add ability to upload managements to bulk upload 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#288]
* [x] define a format for management data that includes enough information to associate each row with a treatment
  * [ ] use the same format (or as close to as is useful) as is exporting management information (#318)
* [x] write a script that will take this file and generate insert statements that can then be reviewed and run manually
 * given a csv file with citation information, `treatments.name` and fields in the managments table (e.g. `mgmttype`, 'name', 'date', 'units')
 * write insert statement for records in csv file to be entered into `managments_treatments` and `managements` tables
* [x] ~~implement as part of bulk upload~~ (would be nice, but not essential)

* mgmttype should be allowed to be any string from managements.mgmttype or variables.name 
* if matches variables.name, should also match variables.units

**Comment by gsrohde** [comment]
@dlebauer 

I have a draft script that will turn something like this:

```
citation_author,citation_year,citation_title,treatment_name,mgmttype,level,units,date
Acaroglu,2005,The cultivation and energy balance of Miscanthus x giganteus production in Turkey,Fertilized (50 kg N ha-),planting (plants m-2),1.5000,plants m-2,1989-05-01
Acaroglu,2005,The cultivation and energy balance of Miscanthus x giganteus production in Turkey,Fertilized (100 kg N ha-),planting (plants m-2),1.0000,plants m-2,1996-04-01
Acaroglu,2005,The cultivation and energy balance of Miscanthus x giganteus production in Turkey,Fertilized (150 kg N ha-),planting (plants m-2),2.0000,plants m-2,1989-05-01
Acaroglu,2005,The cultivation and energy balance of Miscanthus x giganteus production in Turkey,Fertilized (200 kg N ha-),planting (plants m-2),1.5000,plants m-2,1989-05-01
```

into this:

```
START TRANSACTION;
INSERT INTO managements (citation_id, date, dateloc, mgmttype, level, units, notes) VALUES (150, '1989-05-01', 9.000000, 'planting (plants m-2)', 1.500000, 'plants m-2', '');
INSERT INTO managements_treatments (treatment_id, management_id) VALUES (2270, LASTVAL());
COMMIT;
START TRANSACTION;
INSERT INTO managements (citation_id, date, dateloc, mgmttype, level, units, notes) VALUES (150, '1996-04-01', 9.000000, 'planting (plants m-2)', 1.000000, 'plants m-2', '');
INSERT INTO managements_treatments (treatment_id, management_id) VALUES (2271, LASTVAL());
COMMIT;
START TRANSACTION;
INSERT INTO managements (citation_id, date, dateloc, mgmttype, level, units, notes) VALUES (150, '1989-05-01', 9.000000, 'planting (plants m-2)', 2.000000, 'plants m-2', '');
INSERT INTO managements_treatments (treatment_id, management_id) VALUES (2279, LASTVAL());
COMMIT;
START TRANSACTION;
INSERT INTO managements (citation_id, date, dateloc, mgmttype, level, units, notes) VALUES (150, '1989-05-01', 9.000000, 'planting (plants m-2)', 1.500000, 'plants m-2', '');
INSERT INTO managements_treatments (treatment_id, management_id) VALUES (2272, LASTVAL());
COMMIT;
```

Remaining things to flesh out:

1. What columns should be required and which should be optional
2. Precise names for columns
3. Which columns can have blanks in some rows
4. Whether to allow specifying citation by doi instead of author/year/title
5. Whether we need to test that a given management already exists (we have a proposed (date, mgmttype) uniqueness constraint that hasn't been implemented)
6. What should happen if a transaction fails when the SQL script is actually run
7. Nicer error output when a citation or treatment is not found
8. Other?

**Comment by dlebauer** [comment]
Answers to above:

> 1. What columns should be required and which should be optional

optional columns: level,units,date
> 2. Precise names for columns

follow convention for bulk upload data

> 3. Which columns can have blanks in some rows

same as optional colums

> 4. Whether to allow specifying citation by doi instead of author/year/title

less error prone to use author/year/title, so this is 'nice to have' but low priority

> 5. Whether we need to test that a given management already exists (we have a proposed (date, mgmttype) uniqueness constraint that hasn't been implemented)

not essential. But within a treatment, could restrict to unique date / managementtype

> 6. What should happen if a transaction fails when the SQL script is actually run

default SQL error messages

> 7. Nicer error output when a citation or treatment is not found

not essential

> 8. How to specify input and output files, and where the script should run (on local machines or on ebi-forecast)

* input file can be passed as argument to the function (.e.g `$ ./insert_mgmts.sh mymgmts.csv`) 
* what are the contents output file? 

> 9. Other?

no, I think the key is to have the script that takes the csv as an argument, that any user with insert permission in the psql server can run

**Comment by gsrohde** [comment]
@dlebauer See pull request #330.

**Comment by gsrohde** [comment]
Pretty sure there's nothing more to do on this so closing.

**Comment by dlebauer** [comment]
@gsrohde can you please provide a minimal documentation (copy-paste help info from the script, link to script and this issue) in the documentation? I've sent an invitation to gitbook where we can migrate all of the documentation. I imagine that there can be a separate chapter for each existing document and there may be a lot of copy paste and migration if that looks easier (it is just plain markdown and you can use text files in your favorite editor).

**Comment by gsrohde** [comment]
@dlebauer See https://dlebauer.gitbooks.io/betydb-documentation/content/data_entry/management_insertion_script.html.  Is this what you had in mind?

**Comment by dlebauer** [comment]
Yes, thank you

**Comment by gsrohde** [comment]
In release 4.2.2.
