### ISSUE TITLE
Site elevation can't be updated on the site edit page

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#296]
When you press `Update`, the elevation reverts to whatever it was originally.

**Comment by dlebauer** [comment]
Okay to remove this field from the edit and new record interfaces.

**Comment by gsrohde** [comment]
I added an error message that says you can't update the elevation _unless_ you also update the latitude or longitude.  (To update _only_ the elevation, the user will have to update one of the other values too and then change it back to what it was.)

@robkooper Do you have any idea why updating the site geometry to `SRID=4326;Point(old_lon, old_lat, new_masl)` and then saving has no effect.  (save returns true in this case even though it doesn't do anything.)

**Comment by gsrohde** [comment]
Fixes were deployed in release 4.2.
