### ISSUE TITLE
Wrong latitude and longitude values

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#300]
Please check and correct if necessary the latitude and longitude values for the sites with site numbers 1259--1266.  For example, if you look at site 1265 (https://www.betydb.org/sites/1265), you will see it has a longitude of 2000.0.  And site 1262 has a longitude of 76.51667, but this should be a negative number (West) not a positive number (East) since it is in Columbia.

**Comment by dlebauer** [comment]
@Lynnicia can you please check - and update if necessary - the lat/lon coordinates for the sites that you entered?

**Comment by Lynnicia** [comment]
@dlebauer Ahh yes, this is an error in BETYdb. For some reason, the longitude keeps changing to 2000. The value 2000 is the elevation as 2000 m. "Plants were grown in the open at a high-altitude site near Cali, Colombia(elevation 2000 m, mean annual temperature 17 °C)." (El-Sharkawy et. al., 1992) I will try to change this now. No latitude and longitude are given for this site.

**Comment by gsrohde** [comment]
@Lynnicia The bug you mentioned has been fixed but hasn't yet been deployed to the production Web site.

**Comment by dlebauer** [comment]
@Lynnicia could you please provide the lat / lon coordinates for these sites; I can update the database manually for now.

**Comment by Lynnicia** [comment]
@dlebauer Treatment Site Site near Cali was assumed to be in the nearest elevation of 2,000 m from the city Cali on Google Maps: https://www.google.com/maps/@3.5049652,-76.5845739,15z/data=!5m1!1e4

**Comment by dlebauer** [comment]
fixed in web interface

**Comment by gsrohde** [comment]
Updated row 1261, which had 0 for the longitude.
