### ISSUE TITLE
Map link does't work in Sites

### ISSUE THREAD

**Issue by zhangwenx** [PecanProject/bety#305]
browser: Firefox 
Go to Data -> Sites -> click on any link under map in Listing Sites, the pop-up window results Not Found.

**Comment by gsrohde** [comment]
This is likely a VM issue.  Unless you set up the VM to be able to connect to external sites, you will get an error when a page needs to do so.  In this case, it is trying to get information from maps.google.com.

**Comment by robkooper** [comment]
The VM used in this case is connected to the internet so this should not be an issue.

**Comment by dlebauer** [comment]
Would it help to post the activity as recorded in the `production.log`?

**Comment by zhangwenx** [comment]
When I click on the map link, the page is loaded as 
"Not Found 
The requested URL /sites/map was not found on this server.
Apache/2.4.7 (Ubuntu) Server at localhost Port 6480"
app is not deployed root context, to /bety instead

**Comment by dlebauer** [comment]
On the betydb.org site, I don't get the error page, but the link doesn't seem to point anywhere. 

I'd suggest removing the link from the page. It is a feature that is 'nice to have' but certainly not essential.

**Comment by dlebauer** [comment]
This will be fixed by Pull Request #314

**Comment by gsrohde** [comment]
Commit fa57d76d will restore functionality of the map link on the listing page for subdirectory deployments.  Pull Request #314 deals with a slightly different issue--the "Map" text on the Show page, which isn't even a link but is just inert text.  We will remove it.
