### ISSUE TITLE
Error message is returned when delete a new added site

### ISSUE THREAD

**Issue by zhangwenx** [PecanProject/bety#306]
Browser: Firefox 
Go through demo PEcAn_Demo_Handout.1.4.0.pdf/Additional material/2.3 (To add a new site). After add a new site, cannot delete this new site. It returns Error message: 
" PG::ForeignKeyViolation: ERROR: update or delete on table "sites" violates foreign key constraint "fk_inputs_sites_1" on table "inputs" DETAIL: Key (id)=(99000000001) is still referenced from table "inputs". : DELETE FROM "sites" WHERE "sites"."id" = $1 "

**Comment by gsrohde** [comment]
The error message now will say "There are still inputs that refer to this site." once fixes are deployed.

**Comment by gsrohde** [comment]
Fixed in release 4.2.
