### ISSUE TITLE
Link to "CF Guidelines" is broken on PEcAn Virtual Machine

### ISSUE THREAD

**Issue by zhangwenx** [PecanProject/bety#308]
Browser: Firefox 
Go to Data -> Variables -> Edit record: C F Guidelines is a broken link that next page result in "Not Found".

**Comment by dlebauer** [comment]
When I do this, I am re-directed to https://www.betydb.org/guidelines.html (as expected)

Are you using betydb.org, or another instance? 

Could you paste the url that you see when you hover over or copy the "CF Guidelines" link?

**Comment by zhangwenx** [comment]
Yes, I am testing on vm 1.4.2. I think that is why. (  http://localhost:6480/guidelines.html )

**Comment by dlebauer** [comment]
Not sure why this would be an issue on the VM. The page should be in [public/guidelines.html](https://github.com/PecanProject/bety/blob/master/public/guidelines.html).

**Comment by gsrohde** [comment]
This is a problem that only shows up in subdirectory deployments (i.e., home page is at http://hostname/subdir instead of http://hostname).  Fixed in commit b62ea598 using a named route in the link-helper.  Let me know if not!

**Comment by gsrohde** [comment]
Fixed by release 4.2.
