### ISSUE TITLE
Links on Editing covariate page are broken on PEcAn Virtual Machine

### ISSUE THREAD

**Issue by zhangwenx** [PecanProject/bety#312]
The linkes "Extracting information from tables and graphs" , "Extracting data from a figure using R", "Extracting data from a figure using GetData " on the Editing covariate page are broken. The pop-up windows are result in "Not Found".

**Comment by dlebauer** [comment]
@zhangwenx Thank you for checking the buttons in BETYdb. Could you post screenshots?

These links work on BETYdb.org, but it is not clear why they are on this page except as a relic ... These help popular are from a very old version of the documentation and I think the docs--> data entry workflow should be sufficient. More helpful help would be great, if anyone is available to (re) implement such a feature.

I think the solution is to just remove these links from the page.

**Comment by zhangwenx** [comment]
Sure. This is what I get:
![issue312](https://cloud.githubusercontent.com/assets/9668009/7991403/819deb28-0abd-11e5-84d8-727314c19fb9.png)

**Comment by dlebauer** [comment]
This is fixed by #280, which is ready for release in the next version of BETYdb
