### ISSUE TITLE
Citation in Editing Management page consistently take the global citation value on PEcAn Virtual Machine 

### ISSUE THREAD

**Issue by zhangwenx** [PecanProject/bety#313]
Go to the Editing Management page, select any citation value from pull-down menu, then click on update. The updated Management citation value is not same as the selected citation value in editing page, but same as the global citation which is checked from Data->Citation.

**Comment by dlebauer** [comment]
The expected behavior is for the selected citation to refer to the one from which data are being entered. I think the solution is to **remove the field from the managements/edit page**, so that users are not given the choice of selecting another citation.

**Comment by gsrohde** [comment]
Fixed by commit 9b419739: The citation is no longer editable, and it would be changed when you edit other attributes of a management.

**Comment by gsrohde** [comment]
Fixed in Release 4.2.
