### ISSUE TITLE
Shall we take generated documentation files out of the git repostitory?

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#326]
@dlebauer 

Now that we have an easy way to use schemaSpy to generate the template files in app/views/schemas and the associated images files in public/images, I don't see any reason to have these files in the git repository.  Can I remove them?

Alternatively, we could add .gitignore entries to ignore them (we should do this in any case) so that at the very least git won't bother with them.  Then periodically (perhaps whenever a migration is applied to the production database on ebi-forecast) we could generate and check in updated versions.

Please comment and send back to me.

**Comment by dlebauer** [comment]
yes, anything that can be auto-generated does not need to be in the repository.
