### ISSUE TITLE
Error in constraints

### ISSUE THREAD

**Issue by robkooper** [PecanProject/bety#327]
Following functions return an int[] instead of bigint[]

get_input_ids(), get_model_ids() and get_posterior_ids()

@dlebauer @gsrohde  This will prevent anybody that is not EBI to import data. This issue is critical!!!!

**Comment by gsrohde** [comment]
@robkooper 
See pull request #328.  If OK, I'll try to deploy it today.

**Comment by robkooper** [comment]
fixed in pull request.

**Comment by robkooper** [comment]
Thanks Scott for fixing this so quickly.
