### ISSUE TITLE
Clone PFT not working on web interface - BNL

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/bety#335]
I am trying to clone this prior
http://modex.test.bnl.gov/bety/pfts/79/make_clone

I get:

```

The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

```

Is this a problem with my DB?

@dlebauer

**Comment by dlebauer** [comment]
I can't find the server. Does the error occur on the VM? Or at BU?

@robkooper do you recognize this issue?

**Comment by robkooper** [comment]
I get the same errror on pecan.ncsa

This is the error in the log:
```
Processing by PftsController#make_clone as HTML
  Parameters: {"id"=>"79"}
Completed 404 Not Found in 184.1ms

ActionController::RoutingError (No route matches {:action=>"show", :controller=>"pfts", :id=>#<Pft definition: "Created by Shawn Serbin for development and testing...", created_at: nil, updated_at: nil, name: "temperate.Late_Hardwood.optics-copy", parent_id: 79, pft_type: "plant", modeltype_id: 1>}):
  app/controllers/pfts_controller.rb:109:in `block (2 levels) in make_clone'
  app/controllers/pfts_controller.rb:108:in `make_clone'
```

**Comment by gsrohde** [comment]
@robkooper You can easily fix this by interchanging some lines in the PftsController#make_clone action:

Move the lines that copy the associations to be _after_ the `pft.save` line.

**Comment by gsrohde** [comment]
@serbinsh 
This is fixed in the latest release.  If you continue to notice problems after upgrading, please re-open this issue and supply details.
