### ISSUE TITLE
drop formats.dataformat

### ISSUE THREAD

**Issue by mdietze** [PecanProject/bety#336]
This was replaced by formats_variables years ago and is no longer used. It also really clutters the web interface for formats.

**Comment by gsrohde** [comment]
@robkooper This shouldn't be too difficult.  If you want me to take it over, I will.  I'm planning a deployment later today, so let me know soon if you want me to try to include fixes for this.

**Comment by robkooper** [comment]
If you don't mind that would rock.

**Comment by gsrohde** [comment]
Fixed in latest release.
