### ISSUE TITLE
drop inputs_variables

### ISSUE THREAD

**Issue by mdietze** [PecanProject/bety#337]
This was replaced by formats_variables a good while back. Keeping this around is unnecessary and will lead to confusion in the inputs 'edit' webpage, as it will lead some users to fill in values that are not used

**Comment by gsrohde** [comment]
@mdietze @robkooper 

This is scheduled for deletion (I am _right now_ working on deploying a migration that deletes it).  But is there any information contained in `inputs_variables` that needs to be preserved?  I don't think `formats_variables` currently mirrors any of the information that's in `inputs_variables`. (It would seem that if `inputs_variables` associates some variable with an input, then `formats_variables` should associate that variable with the _format_ of that input.  But as far as I can tell, this is never the case.  If this isn't a concern, I'll just delete `inputs_variables` without worrying.)

**Comment by mdietze** [comment]
I just made a copy of inputs_variables so feel free to delete

**Comment by gsrohde** [comment]
Fixed in latest release.
