### ISSUE TITLE
When importing bety: ERROR:  relation "sites" does not exist

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#338]
When importing BETYdb, 

[from wiki](https://github.com/PecanProject/bety/wiki/Automated-Tests#creating-a-new-postgis-enabled-database-template)

```sh
psql -U bety bety < bety.sql
```

I get the error:

> ERROR:  relation "sites" does not exist

**Comment by dlebauer** [comment]
This is because the PostGIS extension is not enabled. Try:

```sh
$ dropdb -U bety bety
$ createdb -U bety bety 
$ psql -U postgres
postgres=# \c bety
bety># CREATE EXTENSION POSTGIS;
bety># \q
$ createdb -U bety bety < bety.sql
```

**Comment by dlebauer** [comment]
also note, to make new databases have the POSTGIS extension by default, you can simply run 

```sh
psql -d template1 -c 'CREATE EXTENSION postgis'
```

**Comment by robkooper** [comment]
Better to use the [load-bety.sh](https://github.com/PecanProject/pecan/blob/master/scripts/load.bety.sh) script. This will take care of creating the database, set the indices and allows you to merge databases from different locations.

**Comment by dlebauer** [comment]
In this case I wanted to duplicate the ebi-forecast ebi_production database, including all of the restricted and unchecked data for analysis, but without any plans to add data or sync.
