### ISSUE TITLE
https://ebi-forecast.igb.illinois.edu/pecan/dump/betydump.psql.gz is no longer available

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#343]
@robkooper, @dlebauer:  Bety's `update.psql.sh` script needs this file to work.  It would be a pain to require Bety developers to install Pecan just to get the sync script.

**Comment by dlebauer** [comment]
To avoid having to install PEcAn, could we change BETY's `update.psql.sh` to (something like)

```sh
#!/bin/bash
wget https://raw.githubusercontent.com/PecanProject/pecan/master/scripts/load.bety.sh -o load.bety.sh
chmod +x load.bety.sh
./load.bety.sh $1 $2 ... $N
```

**Comment by robkooper** [comment]
I would prefer that (btw `$*` is all command line args), this would help me to only have to maintain one script.

**Comment by dlebauer** [comment]
@gsrohde if #344 seems a viable solution, please close this; merge that

**Comment by gsrohde** [comment]
@dlebauer @robkooper 

load.bety.sh doesn't seem to handle the case where you start with an empty database.  I get
```
dlebauer-macbook:script srohde$ ./load.bety.sh 
Checking schema                    : ERROR:  relation "schema_migrations" does not exist
LINE 1: SELECT version FROM schema_migrations ORDER BY version DESC ...
                            ^
EXPECTED SCHEMA version 
Dump is from a different schema, please fix schema in database.
```

**Comment by dlebauer** [comment]
Is this a duplicate of PecanProject/pecan#600?

**Comment by dlebauer** [comment]
The solution there is

```
sudo -u postgres ./scripts/load.bety.sh -c YES -f YES
```

**Comment by gsrohde** [comment]
Yes, this mostly worked (with ./scripts -> ./script).  I had to create a user via the web form that I could log in with and use psql to give that user admin permissions.  I'll read the help and see about writing a wrapper script for Bety developers tailored to the standard use case--refreshing their copy of the database by replacing it with an up-to-date one.

**Comment by robkooper** [comment]
if you want demo users you will need to add the -u flag, see `load.bety.sh -h`

**Comment by gsrohde** [comment]
Yes, I now see that.  I've written a wrapper script tailored to BETYdb developers, so I'm now closing this.
