### ISSUE TITLE
Missing mimetypes for two formats.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#346]
Two rows in the formats table have NULL in the `mimetype_id` column:

```sql
ebi_production=# select * from formats where mimetype_id is null;
     id     | dataformat | notes |         created_at         |         updated_at         |            name             | header | ski
p | mimetype_id 
------------+------------+-------+----------------------------+----------------------------+-----------------------------+--------+----
--+-------------
         29 |            |       | 2013-11-05 22:01:54        | 2015-09-09 19:15:36.907855 | MsTMIP driver               |        |    
  |            
 1000000012 |            |       | 2015-08-28 11:43:19.577417 | 2015-09-11 15:08:57.153142 | Clark Model Demography Data |        |    
  |            
(2 rows)
```

In the second case, the problem arose because of the migration which eliminated the `formats.mime_type` column and replaced it with the `formats.mimetype_id` column.  The value of `mime_type` for that row was "application/x-rds", but this did not match any of the values found in the `mimetypes` table, so an appropriate value for `mimetype_id` could not be assigned.

The obvious fix here would be to edit this format in the BETYdb Rails interface, putting "application/x-rds" in the "New mime type" field.

As for the MsTMIP driver format, as far as I can tell, it was never assigned a mime type.  Should it have one?

**Comment by gsrohde** [comment]
@robkooper , @mdietze 

Please advise if/how you want this fixed or fix it yourself if you wish.

**Comment by mdietze** [comment]
MsTMIP is netcdf

**Comment by gsrohde** [comment]
OK: `MsTMIP driver` now has mime type "application/x-netcdf" and I have inserted a new mime type "application/x-rds" and assigned it to the `Clark Model Demography Data` format.
