### ISSUE TITLE
Eliminate or replace sites.local_time column

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#348]
This column is not often used (appx. 80/1000 rows use it, i.e., are non-null) and not especially useful.  It has type `integer` and presumably gives an offset from UTC.  But this offset is not constant throughout the year for most sites due to daylight savings time.

If we do need timezone information for sites, it would be far more useful to store a bona fide timezone value, such as "US/Central", "America/Chicago", or "CST6CDT" which are "daylight-savings-time agnostic"--that is, they represent a set of offsets (generally a set of size one or two) together with a set of rules for which offset applies at which time of year.  (As you well know, two locations that have the same offset at some times of year may have different rules for when that offset changes.)

PostgreSQL provides a view `pg_timezone_names` that provides a list of time zone names.  Besides a `name` column, it has columns `abbrev`, `utc_offset`, and `is_dst`, which I'm assuming change depending upon the time of year when you do the query.  For example, right now the view contains a row
```sql
              name              | abbrev | utc_offset | is_dst 
--------------------------------+--------+------------+--------
 America/Chicago                | CDT    | -05:00:00  | t
```
but I assume that when we switch back to standard time it will say
```sql
              name              | abbrev | utc_offset | is_dst 
--------------------------------+--------+------------+--------
 America/Chicago                | CST    | -06:00:00  | f
```
I recommend that if we do store time zones, that we choose names from this table.

**Comment by robkooper** [comment]
Lets just use UTC as are times and make this field a string so we can enter the offset. Best is not to use names but offsets, such as +06:00 or -01:45. See also https://github.com/PecanProject/pecan/issues/602 and https://github.com/PecanProject/pecan/issues/603

**Comment by gsrohde** [comment]
My recommendation: Get rid of the `sites.local_time` column, which is poorly named and not very useful since any given site won't have a constant offset anyway.  Replace it with `sites.timezone_name` which would contain daylight-savings-time-agnostic timezone names like those in the `name` column of `pg_timezone_names`.  This could be automatically populated for sites having lat/lon information by (temporarily?) adding a table of named timezone regions (see http://efele.net/maps/tz/world/) and using PostGIS queries to find the timezone name from the site coordinates.

See issue #356 for how we might actually use this field.

**Comment by gsrohde** [comment]
This was part of Release 4.9.  The column is named `sites.time_zone`.
