### ISSUE TITLE
Simple methods for uploading a non-point geometry

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#367]
It would be useful to have 

1. A way to upload a csv with columns `[lat,lon]` or `[lat,lon,elevation]` 
2. A GUI interface that allows users to draw polygons when defining a site. For example, betydb.org/sites/new allows a user to drop a pin to define the lat and lon. 

This is the current interface:

![image](https://cloud.githubusercontent.com/assets/464871/11226277/8a89c5cc-8d44-11e5-9ee8-786403ff7b89.png)

It would be nice if a user could easily draw a bounding box or polygon when defining a site. I think that both the ISDA and CyberGIS groups have developed such interfaces.

**Comment by dlebauer** [comment]
The script Scott wrote for inserting managements could be a good place to start (though the insert is less complex). 

https://github.com/PecanProject/bety/blob/master/script/insert_managements.rb

**Comment by dlebauer** [comment]
Awaiting feedback from @robkooper and @yanliu-chn on proposed or alternative implementation

**Comment by max-zilla** [comment]
First draft of a *command-line* python script to assist in uploading of geometry is committed in my own fork here:
https://github.com/max-zilla/bety/blob/edc50ed8ec8ae03126b510935849ed376d0d8383/script/buildSQLGeom.py

**Comment by dlebauer** [comment]
This works as expected. Please add documentation and close.

**Comment by gsrohde** [comment]
@max-zilla Could you check if this can be closed?  I think your latest changes were included in Release 4.6 (commit aad55f1bc211734b9abd7d2a3c1b7d7a1e94fdc3 from Mar. 16).

**Comment by max-zilla** [comment]
@gsrohde Yes, I believe this can be closed now. Need to flesh out documentation still but there are separate issues for that.
