### ISSUE TITLE
Allow separate instances to customize UI elements 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#368]
It would be great if users could have a simple text file that can be edited for customizing some elements of the user interface.

Ideally, we could a) use some conventions and b) coordinate this with customization of Clowder and interfaces (@robkooper?) and other tools within NDS (?)  

Key customizations are necessary; 'nice to have' customizations would be nice, if it is easy to do. From what I've seen in Jekyll, passing variables around isn't difficult. 

In Jekyll and some Ruby apps this is done via a local `config.yml` file. These seem very easy for non-ruby developers (e.g., me) to understand and modify. There are alternative ways to implement this feature but simplicity is important. (there is also a Ruby Gem http://www.rubydoc.info/gems/configatron/4.5.0 )

### Key customizations:

1. website title [`spec/features/static_integration_spec.rb`](https://github.com/PecanProject/bety/blob/master/spec/features/static_integration_spec.rb)
2. website description
1. data citation (can be blank)
2. contact information
3. git sha in footer and also version number
4. powered by betydb with link back in footer
<img width="412" alt="screen shot 2016-09-28 at 3 58 08 pm" src="https://cloud.githubusercontent.com/assets/464871/18932061/73192290-8594-11e6-8607-3f9f818f275d.png">

5. model output maps removed from all instances except betydb.org

### "Nice to have:

1. color scheme
1. sponsor logos
3. photograph on home page
4. descriptive paragraph
5. link to associated instance of PEcAn

![image](https://cloud.githubusercontent.com/assets/464871/11227002/0cfd6e42-8d49-11e5-8285-028966e16b9d.png)

### Misc updates (not on per-site customization, just while you are in there)

1. Move search bar on home page in line with the "Welcome to BETYdb", widen text. 
2. Change name of access level 2 from  'EBI' to 'Internal'

**Comment by max-zilla** [comment]
Is there any concern about others branding this to the point it's unrecognizable? I assume there are some elements that must be present, e.g. BETYdb identification and such. We may want some required info that can't be removed or hidden.

**Comment by dlebauer** [comment]
Do you think that a 'powered by BETYdb' along with links to the software
license and the github repository would suffice?

The aims are to facilitate scientific discovery and attribution.

**Comment by max-zilla** [comment]
That would address my primary concern - making sure there's a path back to the project github at the very least. Even a clickable grayscale BETYdb logo being included where Illinois and Berkely are in the image above would be enough, I think.

**Comment by dlebauer** [comment]
yes. we may also wish to cite funding agencies and participating
institutions, but we can move this to a separate (static) about page.

**Comment by dlebauer** [comment]
do something like clowder, 

e.g. have powered by betydb link back to betydb.org/about, where we can host https://dlebauer.gitbooks.io/betydb-documentation/content/index.html ...  or this could be under /documentation.

**Comment by gsrohde** [comment]
Release 4.5 now allows customizing contact information (see release notes: https://github.com/PecanProject/bety/releases/tag/betydb_4.5).

**Comment by gsrohde** [comment]
Another thing that could be customized is the base page to the pecan installation referenced by the "Results" links on the Workflows page (see issue #332).

**Comment by gsrohde** [comment]
We've done some basic customization. @dlebauer I'm putting this on hold and assigning to you pending any specific instructions about what features should be added next.  I think there are higher priorities right now.

**Comment by gsrohde** [comment]
@dlebauer, @max-zilla, @robkooper, and anyone else interested: I've made draft changes extending the customization options.  You can see them at https://github.com/PecanProject/bety/pull/447.

Please let me know if you think some things should work differently, if there are things I've left out, or even just if you think a key is badly-name or the name is misleading.

**Comment by rachelshekar** [comment]
this looks good.  we'll create a new issue for additional features

**Comment by gsrohde** [comment]
For additional pending issues, see new issue https://github.com/PecanProject/bety/issues/469.
