### ISSUE TITLE
Error message is returned when deleting a new added input

### ISSUE THREAD

**Issue by bcow** [PecanProject/bety#370]
Usual error:
"We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly."

**Comment by dlebauer** [comment]
@gsrohde would it be difficult to have administrative users notified of errors when the error indicates that this is the case? Or else change the message to lower expectations?

**Comment by gsrohde** [comment]
Changing the message would be easy.  It could refer to the Feedback tab, which has a button for reporting a problem.  In the long term, a log-monitoring system might make sense.

**Comment by gsrohde** [comment]
I couldn't replicate this problem on a test machine.

@bcow Could you go in and edit the input you were trying to delete and add "--Please Delete" to the input name?  That way I can see the exact instance of the problem without worrying about deleting the wrong input.

If for some reason you aren't able to edit it, then could you provide an exact description of the input you want deleted that uniquely identifies it?

**Comment by bcow** [comment]
Ok this is an example of an entry I'd like to delete: 
https://psql-pecan.bu.edu/bety/inputs/1000000546
I was able to edit it, but still can't delete. 
@mdietze also couldn't delete it.

**Comment by dlebauer** [comment]
... seems the default guestuser on that machine doesn't work. @bcow could you provide a screenshot or a login? @gsrohde would the output in production log help?

**Comment by gsrohde** [comment]
Yes, the production log would help.  So would a login.  A screenshot of the "We're sorry" page wouldn't be all that useful.

**Comment by bcow** [comment]
What do you need a screenshot of?

**Comment by gsrohde** [comment]
A screenshot of the Show and Edit pages (with the "Show related ..." sections expanded) for the record you are trying to delete might be somewhat useful.

**Comment by bcow** [comment]
<img width="521" alt="screen shot 2015-11-30 at 2 15 29 pm" src="https://cloud.githubusercontent.com/assets/5503595/11481690/ebb3e882-976c-11e5-9456-a9ec7f614bf7.png">

<img width="827" alt="screen shot 2015-11-30 at 2 15 56 pm" src="https://cloud.githubusercontent.com/assets/5503595/11481687/e670f46e-976c-11e5-97c1-6f2797e5c502.png">

**Comment by gsrohde** [comment]
@bcow I think this problem has to do with the removal of the inputs_variables table.  I had to make some changes to the Rails code to accommodate this but missed a few things.  I think the latest commit fixes this.  So you can probably do a "git pull" and then restart the Rails server and all will be well.

If you want to be more cautious, go into the command line interface, cd to the the directory that is at the top of your Rails tree and run the following two commands and send me the output:

```
git log | head -n1
bundle exec rake db:version
```

One other thing to be aware of is that you may not be able to delete an input that is the parent of another input.

**Comment by mdietze** [comment]
Just did the pull and was able to do a delete without error. @bcow can you verify that it works for you as well and if so close the issue? Thanks @gsrohde for the quick turn around.

**Comment by bcow** [comment]
Works perfectly - thanks!
