### ISSUE TITLE
Allow new users to request changes to their own access levels

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#377]
When I sign up with default access level, then edit my user record, I can select page access Administrator and data access Restricted.

The interface says "Successfully updated" even though records are not updated. The user/edit interface should be the same as the user/new interface in that it should send a request to the administrator(s).

**Comment by gsrohde** [comment]
@dlebauer See pull request #378 and notes there.

**Comment by gsrohde** [comment]
Fixed by release 4.5.
