### ISSUE TITLE
Bulk Upload Not accepting File

### ISSUE THREAD

**Issue by abstewa2** [PecanProject/bety#391]
@dlebauer, when uploading this file: ( a shortened version of the original)

[observations.txt](https://github.com/PecanProject/bety/files/161748/observations.txt)

To this website:
http://pecandev.igb.illinois.edu/terra-test/bulk_upload/display_csv_file

The same issues arise that happened with the Phenotypes file. 

In this file we are missing the variables:
**normalized_difference_vegetation_index ratio , citation_author, citation_year, citation_title, cultivar, species, sitename, plotid, date**

All the other variables on the excel sheet match variables we have in the system already.

This is the image I get:

![image](https://cloud.githubusercontent.com/assets/17127438/13577334/907cc32a-e457-11e5-9798-04271b5bc563.png)

**Comment by dlebauer** [comment]
@abstewa2 
* sitename should concatenate both the sitename  and plot id so that it matches the sites in the database.
* I have added a variable with the name "NDVI"

**Comment by abstewa2** [comment]
![image](https://cloud.githubusercontent.com/assets/17127438/13580373/94f5fcfe-e467-11e5-91fd-85da9659bbdb.png)


@dlebauer , this is the screen I get now that I have fixed everything. I copied only the values in the cells like you wanted and deleted the cells with the formula in them. The rows that appear (first column) for some reason I cant seem to delete. They aren't in my original excel sheet however they show up when I upload it into Pecandev.

**Comment by abstewa2** [comment]
The rows appear to be a feature of the bulk upload. They show up on the other excel sheet also once uploaded into Pecandev

**Comment by gsrohde** [comment]
@abstewa2 The problem is that none of the column headings in your file correspond to variable names in the `trait_covariate_associations` table.

**Comment by dlebauer** [comment]
@abstewa2 see http://pecandev.igb.illinois.edu/terra-test/trait_covariate_associations for list of valid variable names. I've added the variables that are in the file, but the names need to be changed.

**Comment by abstewa2** [comment]
Okay, I will change the names and try again.

**Comment by gsrohde** [comment]
@abstewa2 Can this be closed?

**Comment by abstewa2** [comment]
below I have attached the screen I receive when I upload this file: 
[observations finished shortened summer.txt](https://github.com/PecanProject/bety/files/283199/observations.finished.shortened.summer.txt)


![image](https://cloud.githubusercontent.com/assets/17127438/15559965/62cb585e-22ac-11e6-9eec-e0822e66fa58.png)


to https://terraref.ncsa.illinois.edu/bety-test/bulk_upload/display_csv_file

 I changed the variable names so that they match what is in the betydb variables table and for some reason it wont accept some variables still. ( sitename, biomass_root_total, precipitation_flux, and LeafT)

**Comment by abstewa2** [comment]
Sorry it took me so long to get back to this. let me know what the issue is and I will fix it and get it uploaded by the end of this week.

**Comment by gsrohde** [comment]
@abstewa2 Here are the reasons for the problems:

* sitename: Although "sitename" _is_ the name of the column in the sites table containing the values that these names must match, the correct column heading to use in the CSV file is "site".  When in doubt, consult the bulk upload section of the document at https://www.authorea.com/users/5574/articles/6800/_show_article (which you can get to from the BETYdb web app by selecting the "Docs" menu item and choosing "Data Entry" in the sub-menu).  The relevant passage is

  > Site

  > If all of the data in the data set pertains to a single site, that site may be specified interactively.

  > Otherwise, a `site` column is required. The value must match an existing `sitename` column value in the `sites` table of the database. (Letter case, leading and trailing spaces, and extra internal spaces are ignored when searching for a match.)

* Biomass_root_total and precipitation_flux: In order for a variable name to be recognized as the name of a trait variable, it must be listed as a trait variable in the Trait-Covariates Association Table, which is viewable at https://terraref.ncsa.illinois.edu/bety-test/trait_covariate_associations.  Neither of these are.  The database table this represents can't be edited via the Web interface.  Ask David to add these (or ask him to have me do it).

* leafT: Although leafT _does_ appear in the covariates column in the Trait-Covariates Association Table, it only appears in association with traits that are not in the CSV file.  Therefore it is ignored.  If you want it to be considered to be a covariate of one or more of the traits you have in the CSV file, you must add an association to that trait to the Trait-Covariates Association Table.  Again, David or I could do this.

**Comment by dlebauer** [comment]
I've added root_biomass to the list with optional covariates depth, root_diameter_min, root_diameter_max

I've also changed a few things: converted units to g/m2,  changed dates to years 1020-1025. Also the file in https://github.com/PecanProject/bety/issues/391#issuecomment-221745169 is tab delimited.
