### ISSUE TITLE
Update app to Rails 5.x

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#398]
* Rails 3.2 is no longer supported; current version is 5.1
   * [Github identifies this as 'moderate' security risk](https://github.com/pecanproject/bety/network/dependencies#6927244); many gems also need to be updated 

Please outline steps required to update BETYdb to Rails 5.x, starting with the bare minimum required as well as nice to have features, alongside estimates of time / effort required.

**Comment by max-zilla** [comment]
@gsrohde reports currently on 4.1

**Comment by dlebauer** [comment]
@gsrohde and @robkooper should there be a release at 4.1 to make sure it works in the wild?

**Comment by robkooper** [comment]
yes please, this way we can check it out

**Comment by craig-willis** [comment]
https://github.com/PecanProject/bety/issues/566

**Comment by max-zilla** [comment]
5.1 deployed for testing. on pecan-dev.

**Comment by max-zilla** [comment]
mostly done. just need PR.

**Comment by max-zilla** [comment]
@robkooper needs to review documentation and we can close.
