### ISSUE TITLE
traits table doesn't show up in schema "full relationship" diagram

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#399]
How to reproduce:

* Go to https://www.betydb.org/schemas?partial=relationships

The "traits" table is missing from the diagram.

**Comment by gsrohde** [comment]
It seems table only appear in this diagram if they contain a foreign key or are referred to by some foreign key.  Foreign key constraints haven't been added for the traits table.  See issue #175.

**Comment by dlebauer** [comment]
This should be resolved when constraints are added; closing now
