### ISSUE TITLE
Model Projection page (/maps) is broken.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#401]
To reproduce:

1. Go to the BETYdb home page.
2. Choose the Model I/O menu item and click on Model Projections.
3. There is no data on the map.  Instead it says: "Data may still be loading. Drag or refresh the page to find out."

**Comment by dlebauer** [comment]
@gsrohde The original table seems to have been corrupted so I re-created the county yields and county costs maps. They are here: https://www.google.com/fusiontables/DataSource?docid=1DAaufoEP405M_MNXAJuLxT-NqSvqQQRf30TRcXs

There are 8 maps to replace, and it should be clear which are which. Please fix this - or show me where to fix it - as soon as you have a chance.

**Comment by gsrohde** [comment]
I don't have permission to access that link.

If you want to work on it, I think the relevant file is `/public/javascripts/mylibs/map.js`.  The `initialize` function sets the layers.  Also relevant may be the file `/app/views/maps/location_yields.html.erb`, which shows the map-selection menu, and the directory `/public/temp_models/`, which contains related CSV files.  But I'm happy to work on this if you want me to.

**Comment by dlebauer** [comment]
Sorry, I have now made the links public ...

**Comment by gsrohde** [comment]
@dlebauer I think I figured out how to update the layers (change the "query/from" attribute to the new docid value and the "options/styleId" attribute to the column number).  But the legend colors don't match the maps, and the Least Cost Crop map is still missing.

If you want to see what I've got so far, log in to http://srohde.ncsa.illinois.edu/bety-testing/.  I think you can get there, though you may need HTTP authentication credentials, which I'll send separately.  Or, If I have my Rails server running, you can just go to http://srohde.ncsa.illinois.edu:3000.

**Comment by dlebauer** [comment]
@gsrohde looks good

Can you also try to get the default legends to show. It should look like [this page](https://www.google.com/fusiontables/embedviz?q=select+col16%3E%3E1+from+1DAaufoEP405M_MNXAJuLxT-NqSvqQQRf30TRcXs&viz=MAP&h=false&lat=36.87871058315865&lng=-92.32115374999995&t=1&z=5&l=col16%3E%3E1&y=2&tmplt=2&hml=KML).

If you click on the tab for each map (in the link from previous comment) and select 'publish' it should show you a few options (the url above, an iframe, or html + js). 




https://www.google.com/fusiontables/embedviz?q=select+col16%3E%3E1+from+1DAaufoEP405M_MNXAJuLxT-NqSvqQQRf30TRcXs+where+col6%3E%3E0+%3E%3D+1+and+col6%3E%3E0+%3C%3D+12&viz=MAP&h=false&lat=36.87871058315865&lng=-92.32115374999995&t=1&z=5&l=col16%3E%3E1&y=2&tmplt=2&hml=KML

**Comment by gsrohde** [comment]
@dlebauer See if the four yields legends look OK now (at same URL).  If so, I'll change the cost ones as well.  Note that I set a minimum of 1 in the yields query (which seems to be the default at https://www.google.com/fusiontables/DataSource?docid=1DAaufoEP405M_MNXAJuLxT-NqSvqQQRf30TRcXs#map:id=3), but if you prefer 0 (or maybe 0.1) I can change it.

Also, I still need a Least Cost Crop map.

**Comment by dlebauer** [comment]
Looks great! - please just delete the least cost crop map. It is complicated to set up.

**Comment by gsrohde** [comment]
@dlebauer OK, I've fixed the "cost" maps and deleted the Least Cost Crop map from the menu.

One more problem I didn't quite notice before: The "Energycane Yield (grid)" layer doesn't show anything.  Unlike the other problem maps, I don't get the "Data may still be loading" messages.

**Comment by dlebauer** [comment]
energycane_yield_grid.png and energycane_yield_grid_legend.png are in [`local/modelout`](https://github.com/PecanProject/bety/tree/master/local/modelout)

**Comment by gsrohde** [comment]
There was a bad path to the former.  This must have been broken for a very long time.  Fixed now and pushed to master.  Are you eager to have this live?

**Comment by dlebauer** [comment]
no rush. it can go in the next release
