### ISSUE TITLE
load.bety.sh doesn't populate trait_covariate_associations table

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#403]
It creates it but it's empty.  From a developer's standpoint, it's inconvenient to have to populate this table manually.  And for users doing synchonization, I don't see any reason why this table should be treated any differently from the others.

**Comment by gsrohde** [comment]
@robkooper Can you prioritize this?  It's a nuisance to always have to copy this table manually.

**Comment by robkooper** [comment]
Need to have https://github.com/PecanProject/bety/pull/422 merged first

**Comment by gsrohde** [comment]
Done.  But I haven't deployed the code yet.

**Comment by dlebauer** [comment]
@gsrohde has this been deployed? #422 has been merged

**Comment by gsrohde** [comment]
@dlebauer Pull request #422 only adds the ids to the table—it's only a preliminary step toward fixing the problem.  I think now @robkooper has to uncomment the commented out code he mentioned in his previous comment in order for things to work.

**Comment by serbinsh** [comment]
@dlebauer @robkooper is there a work around until this is automated? I am running into this issue and may be why I can not use the Bulk Uploader on our instance of BETYdb (modex.bnl.gov/bety)

**Comment by dlebauer** [comment]
@serbinsh workaround to populate the trait_covariate_associations table is to run this:

https://gist.github.com/dlebauer/0000fde0c926e2185380056d0743ee53#file-trait_covariate_associations-sql

**Comment by serbinsh** [comment]
OK, so updating the table using commands like:

```
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('39', '343', 'f', '1');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('492', '343', 'f', '2');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('568', '343', 'f', '3');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('15', '80', 'f', '4');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('4', '80', 'f', '5');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('546', '80', 'f', '6');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('404', '80', 'f', '7');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('38', '80', 'f', '8');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('5', '80', 'f', '9');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('7', '80', 'f', '10');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('546', '81', 't', '11');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('404', '81', 't', '12');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('38', '81', 't', '13');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('4', '81', 't', '14');
INSERT INTO trait_covariate_associations ("trait_variable_id", "covariate_variable_id", "required", "id") VALUES ('5', '81', 't', '15');

....

```


And then trying bulk upload again worked for me so it seems the solution is to populate that table?

**Comment by serbinsh** [comment]
Actually this is how I ran the command, leaving here for posterity 
psql -U bety -d bety -a -f trait_covariate_associations.sql
