### ISSUE TITLE
Add 'experiments' table to provide grouping and temporal context to sites

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#410]
We are planning to use the 'sites' table to store fields, blocks, plots, and the location of individual plants. Most existing sites are points, and here we are moving toward the use of polygons that define plot boundaries, and can be used to search and crop datasets.

The sitegroups table could be used to group sites, but it was designed for distributed networks of sites rather than plots within blocks and/or fields.

Plot boundaries will change with each crop, as will the type and location of experiments. Experiments will provide spatial and temporal context to sites that are being treated as plots and blocks.

The same information _could_ be extracted from the range of dates associated with particular sites / plots, but an experiments table will be a more explicit and understandable way of grouping plots by experiments and treatments. 

BMS already handles 'experiments' well, so we do not need to capture all details (plot number, experimental design, etc) which can be stored there. Here we mostly need a name to look up additional information stored in BMS. For BETYdb, we need to have an experiments table that links to sites and treatments.

Note that the identity of genotypes planted in each plot is not a 'treatment' in the way that BETYdb defines 'treatment'. This will be captured in the traits table by the [cultivar_id, site_id] tuples.

Similarly, the [treatment_id, site_id] tuples will account for randomly assigned treatments. Note that 'sites' can be hierarchical, and each site can contain one or more discrete polygons.

At minimum, the new 'experiments' table should at least contain the following fields: 
- id
- name
- start_date
- end_date
- description

Currently the treatments table will store qualitative information about the treatments and the managements table will store quantitative data about what was done and when.

The `experiments` table can be linked to `treatments` via an `experiments_treatments` table and to `sites` via an `experiments_sites` table.

Here is a quick draft for comment / feedback. New proposed tables are in yellow and existing tables in white. For further information, here are links to a [list of existing tables](https://www.betydb.org/schemas) and a [full ER diagram](https://www.betydb.org/schemas?partial=relationships)):

![image](https://cloud.githubusercontent.com/assets/464871/15031328/6eefead6-121d-11e6-88ea-d508c3607c4c.png)

BMS supports more comprehensive information about experimental design. Once our instance of BMS is up we can import data there. The primary role or the experiments table

**Comment by dlebauer** [comment]
add cultivar_id to experiments_sites

**Comment by dlebauer** [comment]
* no need to add pages for web interface
* add sites_sites table

**Comment by dlebauer** [comment]
@gsrohde can this be closed?

**Comment by gsrohde** [comment]
@dlebauer The three experiments tables were part of release 4.13.  But I see that `cultivar_id` was never added to the `experiments_sites` table as you requested in comment https://github.com/PecanProject/bety/issues/410#issuecomment-217205761.  Do you still want this?

**Comment by dlebauer** [comment]
No, lets not add cultivar_id to experiments_sites. I'll close this issue
