### ISSUE TITLE
Queries slow on millions of records

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#419]
[Added 3-7-2017:]
Here are the tasks associated with this issue:
* [x] Make a migration to convert views to materialized views.
* [x] Run the migration on bety6 (since that is highest priority).
* [x] Set up a cron job on bety6 to refresh views daily.
* [x] Investigate making queries faster without using materialized views and decide if materialized views are the best long-term solution.
* If so:
   * [x] Add migration to code base and incorporate it into a release.
   * [ ] Deploy this release on "our" BETYdb instances and set up cron jobs on each.
   * [ ] Provide instructions and support to maintainers of other instances of BETYdb on setting up a cron job to refresh views.

===========================================================
On the terraref.ncsa.illinois.edu/terra-test instance I've added ~16 million rows. 

A few issues this has caused:
1. When I submit queries via the (original) API, e.g. https://terraref.ncsa.illinois.edu/bety-test/search?search=Sorghum+SLA I get 504: connection timed out
   - [this link](https://www.scalescale.com/tips/nginx/504-gateway-time-out-using-nginx/) shows some parameters that can be tweaked if the default time of 60s is too short, but perhaps optimizing queries will fix this  
2. When I do select queries in BETYdb, it takes a loooong time:

Here are some sample queries that take too long. Now that :

``` sql
select mean from traits_and_yields_view where genus = 'Sorghum';
select mean from traits_and_yields_view where genus = 'Sorghum' and trait = 'SLA'; #same as url in 1 above
select mean from traits where cultivar_id = 7000000009 and variable_id = 15; #similar to above
select distinct trait from traits_and_yields_view;
select distinct sitename from traits_and_yields_view;
select distinct cultivar from traits_and_yields_view;
select mean, sitename, date from traits_and_yields_view where 
    genus = 'Sorghum' and trait = 'SLA' and cultivar_id =  7000000009 and extract(year from date) = 1025;
```

**Comment by robkooper** [comment]
make sure to use explain on some of these queries and try to figure out what happens. The traits_and_yields_view is very expensive since it always does 2 selects that are combined.

**Comment by gsrohde** [comment]
We may want to consider using materialized views (sort of like caching a view so it doesn't have to be regenerated every time).

**Comment by dlebauer** [comment]
@gsrohde I set up daily jobs on bety6 to run 

```sql
refresh materialized view traits_and_yields_view;
refresh materialized view traits_and_yields_view_private;
```

Is there a better way to automate this?

**Comment by gsrohde** [comment]
@dlebauer Did you use a cron job?  If so, which crontab did you use?

I think this is OK as far as it goes, but by themselves, these two commands aren't sufficient: You also need to refresh `traitsview_private` and (if used) `yieldsview_private`.  Moreover, the refreshes should be done in order of dependency unless you want to wait an extra day to see the result of changes to the traits or yields tables.  In other words, use the following order:
1. Refresh `traitsview_private` and `yieldsview_private` (in either order).
2. Refresh `traits_and_yields_view_private`.
3. Refresh `traits_and_yields_view`.

Note that refreshing `traitsview_private` takes a while.

**Comment by dlebauer** [comment]
I did it with Navicat ... of you can do it in a way that doesn't depend on
my desktop computer and works for all instances of BETYdb that would be
preferable. Then I can delete the one on my desktop

**Comment by gsrohde** [comment]
@robkooper I notice the bety6 root crontab is managed by puppet.  Can we have puppet handle refreshing the views as well?  Or should I just put something in my own crontab?  @dlebauer I assume we also want to refresh materialized views on bety7, yes?

**Comment by dlebauer** [comment]
bety7 is lower priority than betydb.org ... can this be added as a general
solution e.g. via migration + rake task?

**Comment by dlebauer** [comment]
Or at least added to documentation in a way that is straightforward to
implement? I suspect other users will want this feature as well.

**Comment by robkooper** [comment]
If you need to update the view, use the cronjob. Only those entries that have a comment in front #puppet will be managed by puppet. You can add any crontab entries at the top you want.

**Comment by dlebauer** [comment]
Just updating bety7 (terraref.ncsa.illinois.edu/bety-test) and refreshing materialized views. This database should be fairly static, but recording the queries in the prescribed order

```r
refresh materialized view traitsview_private;
refresh materialized view yieldsview_private;
refresh materialized view traits_and_yields_view_private;
refresh materialized view traits_and_yields_view;
```

**Comment by gsrohde** [comment]
@dlebauer These commands are now in a script file `(Rails root)/script/cron/refresh_views.psql` in the repository.  I had put such a file on bety6 earlier but neglected or chose not to check it in (and I had the last two lines reversed, meaning an extra day to see view updates).  It's checked in now (though the migration to switch to materialized views isn't yet).

I added a cron job on bety7 to run this nightly.  It's in machine-user postgres's crontab if you want to adjust the frequency or even disable it.  It wouldn't be too hard to elaborate the script somewhat to only refresh the views if something has actually changed since the last time they were refreshed, or only if X number of rows were added or updated since the last time they were refreshed.

**Comment by dlebauer** [comment]
I'm also experimenting with changed the TIMEOUT parameter in /etc/apache2/apache2.conf from 300 to 600 s (on bety7 which, with >4million records, is the only db having these issues at the moment.

```sh
sudo nano /etc/apache2/apache2.conf
sudo /etc/init.d/apache2 restart
```

**Comment by dlebauer** [comment]
Next I am also going to try to add an index

```sql
create unique index traits_and_yields_view_trait_index on traits_and_yields_view (trait);
```

**Comment by dlebauer** [comment]
At this point, SQL is performant while the API is an order of magnitude slower.

perhaps replace the Ruby json creator under the API with an SQL that exports as json

**Comment by dlebauer** [comment]
Closing: speeding up API will be implemented by https://github.com/PecanProject/bety/issues/516
