### ISSUE TITLE
Add support for an "entity" column in CSV files uploaded via the API.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#437]
@dlebauer The existing API makes an anonymous entity for each row of the CSV file and associates it with each of the traits given in that row.  It is fairly easy to make the API use a supplied "entity" column to give a name to the entity.  But based on your comment here: https://github.com/terraref/computing-pipeline/issues/33#issuecomment-243856164, it sounds like you want more than this.

See if this is an accurate description of what you want: For each row of the CSV file, check the database entities table to see if there is an existing entity whose name matches the value given in the entity column of the CSV file.  If there is not, create such an entity.  Then associate all the traits in that row with the (possibly newly-created) entity having the specified name.

**Comment by dlebauer** [comment]
yes, that is correct. If this is a barcode or other plant identifier, it would make sense for the name to be a key-value pair like `barcode: xyz123` or `plant_id: abc456` to facilitate interpretation.

**Comment by gsrohde** [comment]
@dlebauer I don't treat things like key-value pairs specially: If the user wants "barcode: xyz123" in the `name` column of the `entities` table, it's simply a matter of putting "barcode: xyz123" in the `entity` column of the CSV file.  If you had in mind it working some other way, I'm open to suggestions.

**Comment by dlebauer** [comment]
We can have the Clowder extractors provide data as it should be inserted. In the PlantCV example, we (@nfahlgren) could modify the PlantCV extractor to use the correct identifier. But its probably overkill at this point, as I would expect barcodes to be unique. And if not, appropriate constraints should throw an error.

**Comment by gsrohde** [comment]
> I would expect barcodes to be unique

I assume what you mean is the value of a `barcode` will never be exactly the same as the value of a `plant_id` so that (for now at least) we needn't worry about identifying the values with keys.

**Comment by serbinsh** [comment]
May or may not be relevant but we use barcode for all of our trait/spectra data such that the barcode number (e.g. BNLXXXXX) is unique for each sample and in some cases the barcode links across multiple traits, e.g. SLA, leaf N, and spectra.  It would be great to ingest data and maintain this barcode such that we could export that data and maintain the links or barcode column or when multivariate MA is running we can sample the data sample by sample, which may be important in some cases.

S



On Sep 21, 2016, at 12:33 PM, David LeBauer <notifications@github.com<mailto:notifications@github.com>> wrote:


We can have the Clowder extractors provide data as it should be inserted. In the PlantCV example, we (@nfahlgren<https://github.com/nfahlgren>) could modify the PlantCV extractor to use the correct identifier. But its probably overkill at this point, as I would expect barcodes to be unique. And if not, appropriate constraints should throw an error.

**Comment by gsrohde** [comment]
In release 4.12.
