### ISSUE TITLE
Add a "site containment" table.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#444]
This will be a table with two columns—call them, say, "container" and "member"—each referring to an id in the `sites` table.  It will have a row for each pair of sites `A` and `B` such that site `A`  completely contains site `B`, that is `ST_Contains(A.geometry, B.geometry)`.  This table will essentially serve as a cache of this relationship.  (How the table is populated and kept up to date remains to be determined.)

**Comment by dlebauer** [comment]
closed because functionality handled by experiments and sitegroups tables
