### ISSUE TITLE
Unhelpful "Bulk Upload" error message.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#452]
If you try to upload a file that specifies the citation by author, year, and title, and if you specify values for these that don't match an existing citation, the error message you get is "undefined method `empty?' for nil:NilClass".

**Comment by dlebauer** [comment]
@gsrohde this issue is poping up ... how hard would it be to resolve this?

Both @ZongyangLi and @NewcombMaria have run into it

**Comment by gsrohde** [comment]
@dlebauer I can't quite remember what's going on with this issue.  It would help to have a sample file from @ZongyangLi and @NewcombMaria to test it out.  It might be an easy fix.

**Comment by dlebauer** [comment]
Here is a sample: [issue452.txt](https://github.com/PecanProject/bety/files/1218883/issue452.txt)

**Comment by dlebauer** [comment]
After removing the first three columns the upload proceeds as expected (throwing an error b/c the cultivar in the sample file no longer exists) 
[issue452-working.txt](https://github.com/PecanProject/bety/files/1218960/issue452-working.txt)

**Comment by gsrohde** [comment]
Resolved by release 4.19.  Closing.
