### ISSUE TITLE
Extend the Bulk Upload Wizard to allow specifying time of day of trait measurements

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#453]

**Comment by dlebauer** [comment]
Does the API already support this?

**Comment by gsrohde** [comment]
Yes.  The API allows you to use either just the date or the date-with-time and allows you to use either local time (site time) or UTC.

**Comment by dlebauer** [comment]
@gsrohde thanks for the clarification. I think that will be sufficient for now, so we can mark this as lower priority.

**Comment by gsrohde** [comment]
Implemented by PR #557.

**Comment by gsrohde** [comment]
Superseded by issue #545.  Closing.
