### ISSUE TITLE
Redirects are misconfigured on ebi-forecast

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#454]
To demonstrate this problem, try the command

``` bash
curl -L https://betydb.org/citations
```

(You can also just try putting `https://betydb.org/citations` in your browser address box.  But putting `betydb.org/citations` in the browser box will probably work.)

The result will be

``` bash
curl: (6) Couldn't resolve host 'www.betydb.orgcitations'
```

In other words, the forward slash between the host and the path is missing upon redirection.  Instead, one should get the Login page, or, if credentials are provided in the command with the `-u <login>:<password>` option, one should get the Citations page.

Note that

``` bash
curl -L https://www.betydb.org/citations
```

_does_ work.

**Comment by dlebauer** [comment]
@gsrohde what is the solution? Is this true for api/citations endpoint too?

**Comment by gsrohde** [comment]
@dlebauer I think this is probably an Apache configuration problem.  I'll take a quick look at it and then turn it over to David Slater to fix.

This problem _does_ affect the API endpoints as well.

In the interim, the best solution is to always include the `www` in the URL.

**Comment by gsrohde** [comment]
@dlebauer One additional note: https://www.betydb.org is the _canonical_ URL for this BETYdb instance.  If you type https://betydb.org or http://www.betydb.org or http://betydb.org, you will be redirected to https://www.bety.org _and the URL in your browser address box will automatically change to this._  Moreover, if you do `curl "https://betydb.org"`—that is, use curl without the `-L` option, you will just get a "301 Moved Permanently" result.

If you want things to work differently—for example, make https://betydb.org the canonical URL or have the two URLs treated equally with neither being redirected to the other—I think this is possible, but we need to let David Slater or whoever is now handling this know.

**Comment by gsrohde** [comment]
Fixed.
