### ISSUE TITLE
Allow Bulk Upload Wizard user to specify method globally

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#470]
* could have one or more traits per row associated with the same method
* add trait - method associations to confirmation page

**Comment by gsrohde** [comment]
Implemented by PR #557: For trait uploads, the "Specify Upload Options and Global Values" page will display a select box for each trait variable, allowing the user to associate a method with it.

**Comment by gsrohde** [comment]
This is superseded by issue #545, which has more discussion.  Closing.
