### ISSUE TITLE
Add "experiments" new, edit, and show pages

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#471]
There should be pages to define, edit, and show 'experiments' (added in #410) within the BETYdb UI.

This should allow users to fill out the following fields:

* name 
* start_date
* end_date 
* description (description of experiment) 
* design (description of experimental design)

Start date and end date can be simple drop downs. 
Design and description should be larger text boxes.

Once an experiment is created, users should also be able to associate sites (plots) similar. This functionality can be exactly the same as the sitegroups page.

**Comment by gsrohde** [comment]
Fixed by release 4.15.
