### ISSUE TITLE
Sites show pages are accessible without logging in.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#474]
For example, without logging in, visit https://www.betydb.org/sites/580.

**Comment by dlebauer** [comment]
I think this is a feature not a bug ...

**Comment by gsrohde** [comment]
That occurred to me.  The main thing is that the behavior is not uniform across the various "metadata" tables: You can view individual sites and individual species without logging in but not individual citations.  And you can't view the sites list without logging in.  Perhaps not worth worrying about though.  Close if you see fit.
