### ISSUE TITLE
Clean up data to allow all constraints currently on terraref bety site to be imposed universally.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#476]
BETYdb on terraref has a migration 20160629194608_add_additional_constraints.rb that is not checked into the repository because of constraint violations in the database for betydb.org. We should clean up this database and then check the migration into the repository.

**Comment by gsrohde** [comment]
BETYdb on terraref has a migration 20160629194608_add_additional_constraints.rb that is not checked into the repository because of constraint violations in the database for betydb.org.  We should clean up this database and then check the migration into the repository.

**Comment by dlebauer** [comment]
is there a list of violations?

**Comment by gsrohde** [comment]
I'm in the process of compiling a list.

**Comment by dlebauer** [comment]
Issue moved to [PecanProject/bety-data #12](https://github.com/PecanProject/bety-data/issues/12) via [**ZenHub**](https://www.zenhub.com/)
