### ISSUE TITLE
species vs specie in new API

### ISSUE THREAD

**Issue by infotroph** [PecanProject/bety#479]
I know this has been discussed in general terms before (e.g. #380), but the new API appears to differ from the original with respect to what's a 'species' and what's a 'specie'. Note that the four calls below return the singular form three times and the plural once. Is this intentional?

https://www.betydb.org/species.json?id=1
[{"specie":{ ... }}]

https://www.betydb.org/species/1.json
{"specie":{ ... }}

https://www.betydb.org/api/beta/species.json?id=1
{"metadata": { ... }, "data": [{"species": { ... }}]}

https://www.betydb.org/api/beta/species/1.json
{"metadata": { ... }, "data": {"specie": { ... }}}

**Comment by gsrohde** [comment]
It should be "species" throughout.  "specie" was a result of a misguided attempt to conform with Rails' default naming rules and in any case never should have been exposed to end users (since it isn't a word!).  It looks like I missed a few places.

**Comment by gsrohde** [comment]
Commit 542028c fixes this for the beta API.

**Comment by gsrohde** [comment]
Fixed by release 4.15.
