### ISSUE TITLE
update TERRA BETYdb landing page

### ISSUE THREAD

**Issue by rachelshekar** [PecanProject/bety#480]
on https://terraref.ncsa.illinois.edu/bety/ 

- [x] change the default text in the search box from "EX: Panicum Nitrogen" to "EX: Sorghum MAC" [will take effect when a new release is pushed to the Terra Ref site]
- [x] remove Model I/O from menu - this refers to EBI data [will take effect when a new release is pushed to the Terra Ref site]
- [x] fix footer image display (remove sorghum image if that is easiest)
- [x] make sure sponsor logos appear nicely
- [x] Change title to "TERRA REF Phenotype Database" (removing BETYdb) [see note below]

**Comment by gsrohde** [comment]
I changed "Phenotype Database" to "TERRA REF Phenotype Database" in the site identification markup but I didn't remove the BETYdb.  This is the name we use to refer to the Rails Web application and the database schema used by both the EBI and the TERRA REF databases.  I was partly following the model of David's Gist here https://gist.github.com/dlebauer/cfd4bb6de70d8ae75bec6804d8c3b16a/revisions where he changed "<strong>TERRA REF</strong> BETYdb <small><strong>Phenotyping</strong>Database</small>" to "<strong>BETY</strong>db <small><strong>Phenotype</strong> Database</small>".  The BETYdb name is used other places in the site (twice in the footer) and I wasn't prepared to drop all references to BETYdb willy-nilly.

**Comment by gsrohde** [comment]
Keeping this open pending further improvement to sponsor logos.

**Comment by gsrohde** [comment]
Logos improved.  Closing.
