### ISSUE TITLE
Add experiments table to data menu in the BETYdb Rails app.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#488]
Add link to /experiments to Runs menu:

![image](https://user-images.githubusercontent.com/464871/29419768-96ffb27e-8335-11e7-9ee4-30097e1cdc17.png)

**Comment by dlebauer** [comment]
Yes

**Comment by dlebauer** [comment]
closing; implemented by has been implemented by https://github.com/PecanProject/bety/commit/a9b64d50f9bef772e66488aebcf12b39542c2629 and deployed
