### ISSUE TITLE
You can't get a list of related sites for an experiment in the BETYdb Rails app.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#489]
@dlebauer Is this a needed feature?

**Comment by dlebauer** [comment]
Nice to have if / when you are updating the show page but not essential (yet).

**Comment by dlebauer** [comment]
Appears to be implemented, based on discussion in https://github.com/terraref/computing-pipeline/issues/349, e.g. 

https://terraref.ncsa.illinois.edu/bety/api/beta/experiments?key=9999999999999999999999999999999999999999&limit=none&associations_mode=ids

returns associated ids from the sites table
