### ISSUE TITLE
Missing variables in betydb.org sites table?

### ISSUE THREAD

**Issue by samsrabin** [PecanProject/bety#492]
`betydb_query(table = 'sites')` returns a table with only 8 columns: city, country, geometry, greenhouse, notes, sitename, state, and time_zone.

**Comment by infotroph** [comment]
You can get more detail by using the [beta API ](https://www.betydb.org/api/docs/beta/sites.html), either for one call like `betydb_query(table = "sites", api_version = "beta")`, or `options(betydb_api_version = "beta")` to set it for the whole session.

If you're interested in more detail about a particular item, the single-record view (e.g. `betydb_record(id = 668, table = "sites", api_version = "beta")`) often has more detail than the table query, though not as much for the sites table as for some others.

**Comment by samsrabin** [comment]
Okay, thanks. This can be closed.
