### ISSUE TITLE
Problems with data from Dalianis et al. (1994)

### ISSUE THREAD

**Issue by samsrabin** [PecanProject/bety#494]
This affects all yield records from citation_id 193; i.e., yield records 912–939.

(1) All the yield records are listed as Elephant Grass (specie_id = 1477, cultivar_id = 75) when nearly half of them should actually be Giant Reed (specie_id = 1842, cultivar_id = 73). The Giant Reed yield records are 912–915, 921–924, and 930–933.

(2) This citation has no treatments associated with it in the citations_treatments table. The treatments described in the paper correspond to the following existing treatments:
- Nfert 60 kg N ha-1/Irrigation 300 mm/Elephant Grass
- Nfert 240 kg N ha-1/Irrigation 300 mm/Elephant Grass
- Nfert 60 kg N ha-1/Irrigation 300 mm/Giant Reed
- Nfert 240 kg N ha-1/Irrigation 300 mm/Giant Reed
- Nfert 60 kg N ha-1/Irrigation 700 mm/Elephant Grass
- Nfert 240 kg N ha-1/Irrigation 700 mm/Elephant Grass
- Nfert 60 kg N ha-1/Irrigation 700 mm/Giant Reed
- Nfert 240 kg N ha-1/Irrigation 700 mm/Giant Reed

However, the data are only ever presented in the paper as an average of all 4 treatments for each species, or averaged across fertilization treatments for each species + irrigation treatment. The following treatments seem to correspond to these ideas:
- treatment_id = 673 ("dalkgN60I300E, dalkgN240I300E")
- treatment_id = 676 ("dalkgN60I700E, dalkgN240I700E")
- treatment_id = 677 ("dalkgN60I300E, dalkgN240I300E, dalkgN60I700E, dalkgN240I700E")
- treatment_id = 680 ("dalkgN60I300G, dalkgN240I300G")
- treatment_id = 683 ("dalkgN60I700G, dalkgN240I700G")
- treatment_id = 684 ("dalkgN60I300G, dalkgN240I300G, dalkgN60I700G, dalkgN240I700G")

But again, none of these dalkgN* treatments are associated with citation_id = 193.

(3) None of the yield records have a treatment associated with them.

(4) None of the dalkgN* treatments have any managements associated with them. The ones that are separated by irrigation (ids 673, 676, 680, and 683) should have irrigation managements added for each year of the experiment. I'm not sure how the "lumped together" managements should be treated.

So far I am unable to edit yield records as described in #486.

- [ ] Change yield records 912–915, 921–924, and 930–933 to Giant Reed.
- [ ] Associate all listed treatments with Dalianis et al. (1994; citation_id = 193). _(How?)_
- [ ] Associate all Dalianis et al. (1994) yield records (yield_id 912–939) with appropriate dalkgN* treatments.
- [ ] Add irrigation managements to treatments with treatment_ids 673, 676, 680, and 683.
- [ ] Determine how to deal with "lumped together" treatments.

**Comment by dlebauer** [comment]
Issue moved to [PecanProject/bety-data #11](https://github.com/PecanProject/bety-data/issues/11) via [**ZenHub**](https://www.zenhub.com/)
