### ISSUE TITLE
Travis is failing with 'relation "experiments" does not exist'.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#501]
* [x] Update `test_structure.sql` to match `production_structure.sql`.
* [ ] Put a note in the documentation for upgrading the canonical (EBI) BETYdb Rails site that both `production_structure.sql` and `test_structure.sql` need to be updated whenever the database schema changes.

@robkooper Can you look at this when you get a chance.  For now, I made a branch called `travis_kludge` which is like `master` with the experiments controllers removed.  This makes Travis pass.

**Comment by robkooper** [comment]
Can you link to the failing build?

**Comment by gsrohde** [comment]
https://travis-ci.org/PecanProject/bety/builds/219465407

This is the first build on master that fails for this reason, I believe.  The problem is that the file app/controllers/api/beta/experiments_controller.rb requires the experiments table to be there: On my own copy of BETYdb, if I remove the experiments table, RSpec will crash.  If I then remove this file, RSpec will run again.

**Comment by robkooper** [comment]
Looks like that `bundle exec rake db:structure:load` does not create the experiments table?

**Comment by gsrohde** [comment]
Updated test_structure.sql.  Can be closed after next release.
