### ISSUE TITLE
Check variable and units on Serbin 2012 cuticular conductance data

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#508]
he cuticular conductance values from @serbinsh [2012 paper](http://jxb.oxfordjournals.org/content/63/1/489.full.pdf+html) are all < 1, suggesting these are in the wrong units (most are ~50k, suggesting values from this citation need to be multiplied by ~ 100,000. Units specied in betydb are mmol/m2/s. I am happy to do this if you can confirm the scaling factor.

Or perhaps these are stomatal conductance, per discussion w/ Shawn. I am marking these as in error

```sql
update traits set checked = -1 
   where citation_id = (select id from citations where author = 'Serbin' and title like 'Leaf optical%') and 
   variable_id = (select id from variables where name = 'cuticular_cond_mmol')
```

### Completion Criteria

* [ ] if this is stomatal conductance:

```sql
update traits 
  set checked = 1, 
      variable_id = (select id from variables where name = 'GS') 
  where citation_id = (select id from citations where author = 'Serbin' and title like 'Leaf optical%') 
  and variable_id = (select id from variables where name = 'cuticular_cond_mmol');
```

* [x] if this is a scale error

```sql
update traits 
  set checked = 1, 
      mean  = mean * <scale_factor>
  where citation_id = (select id from citations where author = 'Serbin' and title like 'Leaf optical%') 
  and variable_id = (select id from variables where name = 'cuticular_cond_mmol');
```

**Comment by dlebauer** [comment]
Fixed 

Found it. I shared this with you back in the day: https://docs.google.com/spreadsheets/d/1pGomnjXaB-iyZ2ZSP5vU_52E3ZYQNv4psLyNugKPUHs/edit?usp=sharing
It looks like we can just change these to stomatal_conductance since this is the column that got read into as cut cond
Avg_COND

**Comment by serbinsh** [comment]
Correct, these were values of average stomatal conductance over the course of the A-Ci measurements so these should be set as:

stomatal_conductance
https://www.betydb.org/variables/293

That said, the units need converted since these are in mol H2O m-2 s-1 (basic licor 6400 units) and it looks like they need to be in kgH2O m-2 s-1???

**Comment by dlebauer** [comment]
* 18.01528 mol/g h2o
* 1000 g / kg

```sql
update traits 
  set checked = 1, 
      mean  = mean * 18.01528/1000
  where citation_id = (select id from citations where author = 'Serbin' and title like 'Leaf optical%') 
  and variable_id = (select id from variables where name = 'GS');
```
