### ISSUE TITLE
Pagination issue in BETY web interface when searching species

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/bety#525]
@gsrohde @dlebauer 

Unfortunately I didn't save an example of the correct behavior on the modex.bnl.gov version of BETY before I updated it to the latest version (4.18) but this was not an issue in the previous release.  So note this seems like a new issue.  I also don't know where else this may be an issue, I discovered it when searching for species to add to a PFT through the BETYdb web front end

Basically, if you search for a genus/species, such as Salix in the "Listing Species" search bar, you will get a list of hits back.  Sometimes this list is multiple pages long.  In the previous version of BETY if you selected next or click on one of the other numbered pages it would show you the next set of species associated with that search. Say you clicked on page 3 it would show you the Salix species listed on page 3 of the search.

However it seems in 4.18 it instead now just lists the species already added into the PFT when you go to the next page.  In other words, instead of continuing to show you the search results it instead shows you the species in the PFT, like it looses track of the search past page 1?

Here is an example searching Acer
<img width="401" alt="screen shot 2017-07-21 at 10 36 07 am" src="https://user-images.githubusercontent.com/3067369/28492076-59314c6a-6ea8-11e7-8c1a-0330d28a7518.png">

You go to the next page and now it shows you all the species in that particular PFT?
<img width="318" alt="screen shot 2017-07-21 at 10 35 33 am" src="https://user-images.githubusercontent.com/3067369/28492073-4b1c5066-6ea8-11e7-8b44-5de4d36025d9.png">

**Comment by gsrohde** [comment]
I found a version BETYdb from June 30, 2015 running of our development server, and this problem exists there as well.  So I don't think it's a recent problem.

That said, I'll look into fixes.

**Comment by gsrohde** [comment]
@serbinsh I think this is fixed.  If you pull the latest version of master (and do `touch tmp/restart.txt` in the Rails root directory, if needed), the searches should work correctly.

**Comment by serbinsh** [comment]
OK, when I have a moment tonight I will give that a try

S
-----------------------------------------------------------------------------
On Jul 24, 2017, at 2:17 PM, Scott Rohde <notifications@github.com<mailto:notifications@github.com>> wrote:


@serbinsh<https://github.com/serbinsh> I think this is fixed. If you pull the latest version of master (and do touch tmp/restart.txt in the Rails root directory, if needed), the searches should work correctly.

**Comment by serbinsh** [comment]
@gsrohde that recent push fixed the issue on modex, thanks!  I recommend the update for BETYdb.org as well...since that is where we created the PFT initially...but I suppose all DBs should run that simple update.

**Comment by gsrohde** [comment]
@serbinsh It will go into the next release, which will be "whenever" unless someone tells me this is urgent, and then I will prioritize it.

**Comment by gsrohde** [comment]
Resolved by release 4.19.  Closing.
