### ISSUE TITLE
JavaScript errors on every page change

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#551]
Every time the user goes to a new page, to errors recur:

    Uncaught ReferenceError: GUnload is not defined at onunload

and

    Uncaught Error: jquery-ujs has already been loaded! at Function.error

These show up only in the console.  They may be harmless or they may be a sign that something isn't working properly or has the potential to not work properly.  In any case, they are distracting, particularly when trying to debug other JavaScript problems.

**Comment by dlebauer** [comment]
fixed in #698
