### ISSUE TITLE
Update app to Rails 4.2 (was 4.1)

### ISSUE THREAD

**Issue by craig-willis** [PecanProject/bety#566]
Per TERRA-REF planning meeting, let's complete the update to 4.1 before continuing to 5.x.

Completion criteria:
* [x] Finish ~4.1~ 4.2 upgrade 
* [x] Make PR
* [x] Deploy automated build using containers
* [x] Manual testing with Pecan and TERRA teams
* [x] Get approval for PR and merge
*  Deploy upgrade
    * [x] On terraref/bety
    * [x] On terraref/bety-test
    * [x] On terra-mepp
    * [ ] On ebi-forecast

**Comment by ashiklom** [comment]
Is there a reason we're stopping at 4.1? The current release version is [5.1.4](http://rubyonrails.org/). We don't necessarily have to go that high, but I've been having problems doing `db:migrate` related to [invalid arguments passed to `pg_dump`](https://stackoverflow.com/questions/35999906/pg-dump-invalid-option-i-when-migrating/39130103), which as apparently been [resolved as of rails 4.2.6](https://stackoverflow.com/a/36273109/2477097).

**Comment by robkooper** [comment]
no, the goal is to go all the way to 5, but it seems like a good idea to go to 4.x first, review make sure it works and then focus on getting to 5, so this is just a step towards 5.x

**Comment by max-zilla** [comment]
max is currently testing this.

**Comment by max-zilla** [comment]
scott is working on the 5.0 PR.

**Comment by max-zilla** [comment]
@gsrohde is planning a 4 release tomorrow.
@robkooper requests a PR for v5, he will deploy on PecanDev same as before.
