### ISSUE TITLE
API does not match strings exactly

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#567]
based on the documentation https://pecan.gitbooks.io/betydb-data-access/content/API/beta_API.html

I would expect either

https://terraref.ncsa.illinois.edu/bety/api/v1/sites?key=9999999999999999999999999999999999999999&name=MAC+Field+Scanner+Field

or

https://terraref.ncsa.illinois.edu/bety/api/v1/sites?key=9999999999999999999999999999999999999999&name=MAC Field Scanner Field

To return the site where the name exactly matches the name "MAC Field Scanner Field" 

i.e., I would expect the same response as:

https://terraref.ncsa.illinois.edu/bety/api/v1/sites?key=9999999999999999999999999999999999999999&id=6000000001

However, the API does partial matching and finds 9157 records

### Completion Criteria

* If this is expected functionality and I should use another string to return the correct result, this should be documented, and Python and R clients should be updated.
* Otherwise, the API should be fixed to perform as described in the documentation

**Comment by gsrohde** [comment]
@dlebauer Use "sitename=...".  Using a parameter in the query string that doesn't match any existing attribute of the database table is not an error (perhaps it should be), but neither will it filter anything out.

**Comment by dlebauer** [comment]
sorry. using sitename in this table is frequently confusing!
