### ISSUE TITLE
Graphs for Priors are not regenerated when parameters are edited.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#574]
Steps to reproduce:

1. Visit the show page for a Prior that has an existing graph.  Note the existing parameter values shown in the graph.
2. Click edit.
3. Change the values of one or more parameters.
4. Click update.
5. Click show to see the graph.  Notice that it hasn't changed, and the parameter values listed are the old ones.

**Comment by serbinsh** [comment]
Interesting, on modex.bnl.gov this is not the case.  That is I can edit the params and get updated values and graphs when I click "show"

**Comment by gsrohde** [comment]
Closing—I can't reproduce this problem any more.
