### ISSUE TITLE
Graph images for Priors are not being generated on the terraref Bety site.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#575]
Most likely, the reason is that R—and possibly some needed graphics libraries—are not installed on the server.

**Comment by gsrohde** [comment]
@robkooper At a minimum, R and the library 'ggplot2' need to be installed in order for this to work.  This applies to both the terraref bety and the terraref bety-test sites.

**Comment by max-zilla** [comment]
@robkooper any update here?

**Comment by max-zilla** [comment]
@robkooper poke

**Comment by robkooper** [comment]
```
apt-get install --no-install-recommends r-base-core
Rscript -e 'install.packages("ggplot2", repos = "http://cran.rstudio.com/")'
```

**Comment by gsrohde** [comment]
It seems to be working.  Perhaps bety7 should be updated too though.

**Comment by dlebauer** [comment]
looks good; thanks @robkooper 

deploying to bety7 is low priority; closing now. Assuming this has been added to the bety docker container(?) so this won't happen again?

**Comment by robkooper** [comment]
bety7 is done
