### ISSUE TITLE
Update BETY documentation

### ISSUE THREAD

**Issue by craig-willis** [PecanProject/bety#580]
Because Rails 5 requires extra steps, we need to update the documentation for how to setup BETYdb app and all of the version information is pretty old.

Completion criteria:
* [x] Documentation completed
* [ ] Docs reviewed
* [ ] Deployed via gitbook

**Comment by max-zilla** [comment]
new instructions for setting up BETY on CentOS

**Comment by max-zilla** [comment]
@robkooper will review the documentation prior to release before this is closed.
