### ISSUE TITLE
Can't create or edit Experiments via the BETYdb Web app

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#581]
This problem may have been introduced with the upgrade to Rails 4.

**Comment by dlebauer** [comment]
Just encountered this on terraref.ncsa.illinois.edu/bety is it possible that this affects other pages as well?

**Comment by gsrohde** [comment]
Possible, but I think I've caught all the other places where this might be a problem.

**Comment by gsrohde** [comment]
Fixed by release 5.0.  Closing.
