### ISSUE TITLE
Add explanation of new bulk upload features to GitBook documentation

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#589]
These are the features from issue #545.

**Comment by max-zilla** [comment]
@dlebauer will look at sample in bety repo - https://github.com/PecanProject/betydb-documentation/issues/2

**Comment by dlebauer** [comment]
Looks great … lets move to bookdown!

**Comment by max-zilla** [comment]
bookdown work has been completed and the tech documentation for this just needs to be deployed with updated links.

**Comment by max-zilla** [comment]
Question of where to deploy - GitHub Pages is current thinking. github.io URL.

**Comment by max-zilla** [comment]
see also: ttps://pecanproject.github.io/pecan-documentation/master/

**Comment by max-zilla** [comment]
have a draft done. just need to get it deployed with help from @robkooper 

might deploy somewhere temporarily so Chris Black w/ TERRA MEPP can look at it in the meantime.

**Comment by max-zilla** [comment]
Next steps: where and how will this be deployed. Need @robkooper involvement.

@dlebauer have you reviewed the changes?

**Comment by max-zilla** [comment]
Any updates from anyone? would like to close this.

**Comment by gsrohde** [comment]
I’ve been away from this for awhile.  I’ll take a look and get back to you.

**Comment by gsrohde** [comment]
@max-zilla I just noticed I'd added the "ready for release" tag to this, which would indicate that I finished updating this section of the documentation.  (And even if it's not perfect, it's certainly better and more up-to-date that what is currently live.)  But I wouldn't close this until it is actually deployed (see https://github.com/PecanProject/betydbdoc-dataentry/issues/2) and until links to the documentation in BETYdb are updated to point to the new documentation location.

**Comment by max-zilla** [comment]
@dlebauer and @robkooper to decide where to deploy bookdown

**Comment by gsrohde** [comment]
Bookdown version has been deployed, and links to documentation were updated in release BETYdb 5.2.1.  Closing.
