### ISSUE TITLE
`load.bety.sh` does not automatically track PEcAn updates in Docker container

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/bety#597]
Because `load.bety.sh` is pulled in via a `curl` command in the [Dockerfile](https://github.com/PecanProject/bety/blob/master/Dockerfile#L33-L36), revisions to `load.bety.sh` will _not_ trigger updates to the `bety` Docker container. This means it's very easy for the `bety` Docker container to become out of date with changes to its initialization procedure.

The most straightforward way to fix this is to move the `load.bety.sh` script from `pecan` into `bety` (which, to me, just generally makes more sense).

**Comment by robkooper** [comment]
agree, we can move load/dump scripts to bety instead of pecan.
