### ISSUE TITLE
Unrealistic leaf_respiration_rate_m2 prior 

### ISSUE THREAD

**Issue by istfer** [PecanProject/bety#651]
Prior ID 189 `Unif[0, 100]` is a very wide prior for leaf respiration rate in umol m-2 s-1. 

It could break runs and it might be hard to trace it back to this prior (which actually happened to me before), so it should probably be removed. But it's currently associated with some PFTs, so I'm not sure what is the procedure in that case.

**Comment by dlebauer** [comment]
If you can propose an alternative prior I can update this. I can either reduce the upper bound of the Uniform, or if you can come up with a broad gamma with a biologically reasonable median?

________________________________

**Comment by istfer** [comment]
`197` already seems like a broad gamma with a biologically reasonable median. Maybe we can reduce the upper bound to 10 or so? @serbinsh?

**Comment by serbinsh** [comment]
Indeed, 10 is probably a good upper.

**Comment by serbinsh** [comment]
@istfer there is also 2000000103

**Comment by istfer** [comment]
@serbinsh yep I actually switched to using that one

**Comment by serbinsh** [comment]
Its maybe a little more informative than I would like but for models like SIPNET I find it works pretty well

**Comment by dlebauer** [comment]
OK I’ve updated https://www.betydb.org/priors/189 so upper bound is 10. Can the issue be closed? Should we have an issue to review / update existing priors?

________________________________

**Comment by istfer** [comment]
Thanks David, yes this issue can be closed.

I really liked the prior-reviewing idea.

**Comment by serbinsh** [comment]
@istfer @dlebauer I too would advocate for twice yearly, annual, more often(?) prior review

**Comment by dlebauer** [comment]
We could intermittently bring up sets of priors on our weekly review?

I suspect there is a pun to be had here with priors and scheduling but it is out of my grasp. I’m confident it would be a good one, so go ahead and have a chuckle.
