### ISSUE TITLE
Choose a better list of values for the soil choices on the new site and site editing pages.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#652]
Right now the list of choices is `sandloamy, sandsandy, loamsilt, loamloamsandy, clay, loamsilty, clay, loamclay, loamsandy, claysilty, clayclaypeat`.  Note, among other things, that `clay` is listed twice.  This has been the list since April 4, 2013.  

Prior to that, the list was `sand, loamy sand, sandy loam, silt loam, loam, sandy clay loam, silty clay loam, clay loam, sandy clay, silty clay, clay, peat`.  This seems like a more reasonable list.  I don't know the reason for the change.  This list matches the list laid out in issue #246, which talks about possible constraints on this value. (Right now there are none other than that it be of type `character varying(255)` and not null (but it can be blank).)  I don't remember what discussion, if any, gave rise to the list in issue #246, but perhaps we considered restoring that as the list of possible choices provided in the BETYdb Rails app in addition to establishing a database constraint.

The reason for prioritizing this issue is that I would like to establish a set of ideal soil value choices before adding new sites to the TERRA-MEPP database in connection with https://github.com/terra-mepp/data/issues/12.

@dlebauer Could you please take a look at this and comment?

**Comment by dlebauer** [comment]
We can use the list of soil texture classifications from the USDA soil texture triangle, plus peat, bedrock, and 'other':

![image](https://user-images.githubusercontent.com/464871/61312447-46c4e380-a7ad-11e9-8e0a-a31f05611a36.png)

**Comment by gsrohde** [comment]
Completed by release BETYdb 5.2.1.  Closing.
