### ISSUE TITLE
Errors when building with ruby > 2.3

### ISSUE THREAD

**Issue by robkooper** [PecanProject/bety#664]
Failures:
  1) Bulk Data Upload Various scenarios involving the variable names in the heading of a trait upload file How parsing of variables in the heading works A variable in the heading should be recognized even if it isn't in the trait_covariate_associations table
     Failure/Error: expect(first("div.alert-success")).to have_content("Data from valid-test-data-with-traits-not-in-associations-table.csv was successfully uploaded.")
       expected to find text "Data from valid-test-data-with-traits-not-in-associations-table.csv was successfully uploaded." in ""
     # ./spec/features/bulk_upload_integration_2_spec.rb:525:in `block (5 levels) in <top (required)>'
     # ./spec/features/bulk_upload_integration_2_spec.rb:522:in `block (4 levels) in <top (required)>'
  2) Bulk Data Upload Various scenarios involving the variable names in the heading of a trait upload file How parsing of variables in the heading works Heading variables that are in the trait_covariate_associations table should be recognized as usual
     Failure/Error:
       expect { click_button 'Insert Data' }.to change { Trait.count }.by(2)
                                            .and change { Covariate.count }.by(2)
                                            .and change { Entity.count }.by 1;     # The two rows in the file have the same entity name.
     
          expected `Trait.count` to have changed by 2, but was changed by 0
     
       ...and:
     
             expected `Covariate.count` to have changed by 2, but was changed by 0
     
          ...and:
     
             expected `Entity.count` to have changed by 1, but was changed by 0
     # ./spec/features/bulk_upload_integration_2_spec.rb:555:in `block (4 levels) in <top (required)>'
  3) Bulk Data Upload Tests of notes column functionality A CSV file with a notes column should be able to leave cells in that column blank
     Failure/Error:
       expect { click_button 'Insert Data' }.to  change { Trait.count }.by(2)
                                            .and change { Covariate.count }.by(2)
                                            .and change { Entity.count }.by(1);  # The two rows in the file have the same entity name.
     
          expected `Trait.count` to have changed by 2, but was changed by 0
     
       ...and:
     
             expected `Covariate.count` to have changed by 2, but was changed by 0
     
          ...and:
     
             expected `Entity.count` to have changed by 1, but was changed by 0
     # ./spec/features/bulk_upload_integration_2_spec.rb:581:in `block (3 levels) in <top (required)>'
  4) Bulk Data Upload Tests of notes column functionality Non-empty notes values in a CSV file should be inserted into the database
     Failure/Error: expect(Trait.connection.exec_query(query).first["notes"]).to eq("This was from a western site")
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/features/bulk_upload_integration_2_spec.rb:598:in `block (3 levels) in <top (required)>'
  5) Bulk Data Upload Tests for date support Testing 'date-only' values The date inserted into the database should be the UTC time corresponding to 12am site time on the date specified
     Failure/Error: expect(Trait.connection.exec_query(query).first['hour'].to_i).to eq(0)
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/features/bulk_upload_integration_2_spec.rb:652:in `block (4 levels) in <top (required)>'
  6) CSV file upload works GET /bulk_upload/start_upload should successfully insert data from a file even when headings are not in canonical form
     Failure/Error: expect { click_button 'Insert Data' }.to change { Yield.count }.by 1
       expected `Yield.count` to have changed by 1, but was changed by 0
     # ./spec/features/bulk_upload_integration_spec.rb:78:in `block (3 levels) in <top (required)>'
  7) BulkUploadDataSet Given a valid yields data file insert data should get insertion data
     Failure/Error:
       interactively_specified_values.keep_if do |key, value|
         !(value.empty? || value.nil?)
       end
     
     NoMethodError:
       undefined method `keep_if' for nil:NilClass
     # ./app/models/bulk_upload_data_set.rb:1907:in `get_insertion_data'
     # ./spec/models/bulk_upload_data_set_spec.rb:442:in `block (4 levels) in <top (required)>'
  8) BulkUploadDataSet Given a valid yields data file test rounding should round data to precision
     Failure/Error:
       interactively_specified_values.keep_if do |key, value|
         !(value.empty? || value.nil?)
       end
     
     NoMethodError:
       undefined method `keep_if' for nil:NilClass
     # ./app/models/bulk_upload_data_set.rb:1907:in `get_insertion_data'
     # ./spec/models/bulk_upload_data_set_spec.rb:473:in `block (4 levels) in <top (required)>'

**Comment by gsrohde** [comment]
Should be fixed by PR #665.

**Comment by robkooper** [comment]
Fixes 2.4 and 2.5, still some errors for 2.6, will create a new issue for that.
