### ISSUE TITLE
CSV file downloads are not working

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/bety#674]
Try, for example, https://www.betydb.org/models.

This is an easy fix: upgrade the comma Gem

**Comment by dlebauer** [comment]
for the example, did you mean /models.csv? 

would be nice to have if it is an easy fix, but at some point (if it takes too much work) we can deprecate the original API

**Comment by gsrohde** [comment]
https://github.com/PecanProject/bety/pull/676 should fix this.  It was an easy fix (upgrading a Gem), though not quite so easy to discover.
