### ISSUE TITLE
Problem when registering 

### ISSUE THREAD

**Issue by Chris-Schnaufer** [PecanProject/bety#677]
I just tried registering for TERRA REF BETYdb (https://terraref.ncsa.illinois.edu/bety/) and received the following error:

<img width="993" alt="Screen Shot 2019-08-27 at 11 18 32 AM" src="https://user-images.githubusercontent.com/45463434/63801222-9f1af500-c8c4-11e9-9784-1044fb9d93b9.png">

This looks like a repeat of https://github.com/PecanProject/bety/issues/355

**Comment by dlebauer** [comment]
I think we should implement the fix now so users / maintainers don't get confused. I'll submit a PR for that

Then we can figure out and / or document configuration. 

Options for changing the default mail server are here: https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration; what remote server would you change it to?
