### ISSUE TITLE
API key not get reflected into the db after creation

### ISSUE THREAD

**Issue by koolgax99** [PecanProject/bety#737]
So, I was working on the API key for REST API's wherein I am trying to use API key as an authentication for the API's. But a vital issue i faced was when i created the apikey in my bety dashboard for a user, it did not get reflected in the original database. I got to know this when i was trying to query the users' table in my rstudio.

Here, in the below screenshot I have created the apikey for the "guestuser". 

Now i am trying to print all the details that are present for the guestuser in the db via the below script
![image](https://user-images.githubusercontent.com/55532999/183260490-b1f18089-7341-42ed-93a8-932b2c93586c.png)

Below is the output i am getting after running the script. The apikey column is showing as NA.
![image](https://user-images.githubusercontent.com/55532999/183260528-41788f84-099d-4d59-b296-5f3cd626f956.png)

Can anyone please help me resolve this? I am using the docker version of pecan development

**Comment by robkooper** [comment]
I tried this as well, and used:

```
library(dbplyr)
library(RPostgreSQL)

bety <- DBI::dbConnect(
  DBI::dbDriver("PostgreSQL"), 
  dbname = Sys.getenv("PGDATABASE", "bety"),
  host = Sys.getenv("PGHOST", "postgres"),
  user = Sys.getenv("PGUSER", "bety"),
  password = Sys.getenv("PGPASSWORD", "bety")
)

users <- dplyr::tbl(bety, "users") %>%
  dplyr::filter(apikey != "") %>%
  dplyr::collect()
```

this does return all users with an apikey

**Comment by robkooper** [comment]
also looking at your screenshot and the tbl, the email address is different.

**Comment by robkooper** [comment]
looking at the url, you are probably connected to a different instance of BETY

**Comment by dlebauer** [comment]
Also note: 
- if you press the button labeled 'key' it should generate a new key
- if you post a picture of an API key, it is a potential security issue - likely not much of one if it is a development database, but I think the carya user has elevated permissions (can also be fixed by generating a new key)

**Comment by koolgax99** [comment]
> Also note:
> 
> * if you press the button labeled 'key' it should generate a new key
> * if you post a picture of an API key, it is a potential security issue - likely not much of one if it is a development database, but I think the carya user has elevated permissions (can also be fixed by generating a new key)

Yes sir its a potential security issue but it is a development database. However ill delete the photos and would keep this in mind. Thanks for pointing it out!. 

I solved this issue as i was connected to a different instance of the database.
