### ISSUE TITLE
CSV v0 API is not working

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/bety#747]
This https://www.betydb.org/search.csv?search=Salix used to return a CSV file from traits_and_yields_view.

Now it returns "We're sorry, but something went wrong"

Is this similar to https://github.com/PecanProject/bety/issues/674 which was fixed by upgrading the comma gem: https://github.com/PecanProject/bety/pull/676/files?

**Comment by Yuvraj198920** [comment]
@dlebauer I clicked on the link and it successfully returned the CSV file without any errors. I didn't encounter the message "We are sorry, but something went wrong". This could have been caused by the API experiencing some problems that prevented it from providing the correct response.

**Comment by dlebauer** [comment]
Thanks! You are probably correct, we were having issues at that time
